const chalk = require('chalk')
const fs = require('fs')

global.listallmenu = (prefix, hias, hituet) => {
return`━━━〔 𝑶𝒘𝒏𝒆𝒓 𝑴𝒆𝒏𝒖  〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}self*
⤷ 𐔌  *${prefix}public*
⤷ 𐔌  *${prefix}onlyregis*
⤷ 𐔌  *${prefix}registeronly*
⤷ 𐔌  *${prefix}onlyregister*
⤷ 𐔌  *${prefix}notifregister*
⤷ 𐔌  *${prefix}registernotif*
⤷ 𐔌  *${prefix}notifregis*
⤷ 𐔌  *${prefix}getcase*
⤷ 𐔌  *${prefix}ban*
⤷ 𐔌  *${prefix}unban*
⤷ 𐔌  *${prefix}whitelist*
⤷ 𐔌  *${prefix}unwhitelist*
⤷ 𐔌  *${prefix}blacklist*
⤷ 𐔌  *${prefix}unblacklist*
⤷ 𐔌  *${prefix}delcase*
⤷ 𐔌  *${prefix}listwhitelist*
⤷ 𐔌  *${prefix}listblacklist*
⤷ 𐔌  *${prefix}upswgc*
⤷ 𐔌  *${prefix}cheat*
⤷ 𐔌  *${prefix}cheatall*
⤷ 𐔌  *${prefix}cheatlegendary*
⤷ 𐔌  *${prefix}setppbot*
⤷ 𐔌  *${prefix}setppbotfull*
⤷ 𐔌  *${prefix}setppbotpanjang*
⤷ 𐔌  *${prefix}setbotpp*
⤷ 𐔌  *${prefix}cleartmp*
⤷ 𐔌  *${prefix}deltmp*
⤷ 𐔌  *${prefix}clearcache*
⤷ 𐔌  *${prefix}delcache*
⤷ 𐔌  *${prefix}notifregis*
⤷ 𐔌  *${prefix}addlimit*
⤷ 𐔌  *${prefix}addsaldo*
⤷ 𐔌  *${prefix}adduang*
⤷ 𐔌  *${prefix}redeemset*
⤷ 𐔌  *${prefix}setredeem*
⤷ 𐔌  *${prefix}delredeem*
⤷ 𐔌  *${prefix}redeemdel*
⤷ 𐔌  *${prefix}delsampah*
⤷ 𐔌  *${prefix}pconly*
⤷ 𐔌  *${prefix}gruponly*
⤷ 𐔌  *${prefix}joinchannel*
⤷ 𐔌  *${prefix}outchannel*
⤷ 𐔌  *${prefix}outgroup*
⤷ 𐔌  *${prefix}joingroup*
⤷ 𐔌  *${prefix}autobio*
⤷ 𐔌  *${prefix}inspect*
⤷ 𐔌  *${prefix}autotype*
⤷ 𐔌  *${prefix}autorecord*
⤷ 𐔌  *${prefix}autorecordtype*
⤷ 𐔌  *${prefix}autorecordtype*
⤷ 𐔌  *${prefix}unavailable*
⤷ 𐔌  *${prefix}autoread*
⤷ 𐔌  *${prefix}shutdown*
⤷ 𐔌  *${prefix}pengingat*
⤷ 𐔌  *${prefix}anticall*
⤷ 𐔌  *${prefix}autoswview*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑼𝒔𝒆𝒓 𝑴𝒆𝒏𝒖  〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}jadobot*
⤷ 𐔌  *${prefix}stopjadobot*
⤷ 𐔌  *${prefix}listjadibot*
⤷ 𐔌  *${prefix}cupon*
⤷ 𐔌  *${prefix}exp*
⤷ 𐔌  *${prefix}cekexp*
⤷ 𐔌  *${prefix}cooldown*
⤷ 𐔌  *${prefix}cekdarah*
⤷ 𐔌  *${prefix}limit*
⤷ 𐔌  *${prefix}ping*
⤷ 𐔌  *${prefix}me*
⤷ 𐔌  *${prefix}limit*
⤷ 𐔌  *${prefix}ceklimit*
⤷ 𐔌  *${prefix}buylimit*
⤷ 𐔌  *${prefix}buyglimit*
⤷ 𐔌  *${prefix}cekprem*
⤷ 𐔌  *${prefix}buyglimit*
⤷ 𐔌  *${prefix}mingguan*
⤷ 𐔌  *${prefix}bulanan*
⤷ 𐔌  *${prefix}cekprem*
⤷ 𐔌  *${prefix}daftar*
⤷ 𐔌  *${prefix}register*
⤷ 𐔌  *${prefix}registrasi*
⤷ 𐔌  *${prefix}regmail*
⤷ 𐔌  *${prefix}regismail*
⤷ 𐔌  *${prefix}regmail*
⤷ 𐔌  *${prefix}captcha*
⤷ 𐔌  *${prefix}regkode*
⤷ 𐔌  *${prefix}regcode*
⤷ 𐔌  *${prefix}unreg*
⤷ 𐔌  *${prefix}unregister*
⤷ 𐔌  *${prefix}redeem*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑨𝒏𝒐𝒏𝒚𝒎𝒐𝒖𝒔 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}menfes*
⤷ 𐔌  *${prefix}stopmenfess*
⤷ 𐔌  *${prefix}tolakmenfes*
⤷ 𐔌  *${prefix}balasmenfes*
⤷ 𐔌  *${prefix}start*
⤷ 𐔌  *${prefix}mulai*
⤷ 𐔌  *${prefix}anonymouschat*
⤷ 𐔌  *${prefix}sendprofil*
⤷ 𐔌  *${prefix}lanjut*
⤷ 𐔌  *${prefix}neks*
╰━━━━━━ 𑁍 ━━━━━━╯͙

​━━━〔 𝑩𝒆𝒓𝒊𝒕𝒂 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  ${prefix}kompas
⤷ 𐔌  ${prefix}tribunnews
⤷ 𐔌  ${prefix}liputan6
⤷ 𐔌  ${prefix}sindonews
⤷ 𐔌  ${prefix}cnbc
⤷ 𐔌  ${prefix}cnbcindo
⤷ 𐔌  ${prefix}cnbcindonesia
⤷ 𐔌  ${prefix}merdeka
⤷ 𐔌  ${prefix}beritamerdeka
⤷ 𐔌  ${prefix}antara
⤷ 𐔌  ${prefix}antaranews
⤷ 𐔌  ${prefix}beritaantara
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑽𝒐𝒊𝒄𝒆 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}alya*
⤷ 𐔌  *${prefix}kobo*
⤷ 𐔌  *${prefix}tokobo*
⤷ 𐔌  *${prefix}zeta*
⤷ 𐔌  *${prefix}tozeta*
⤷ 𐔌  *${prefix}voicejokowi*
⤷ 𐔌  *${prefix}voiceprabowo*
⤷ 𐔌  *${prefix}voicemegawati*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑴𝒂𝒌𝒆𝒓 𝑴𝒆𝒏𝒖  〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}snapcode*
⤷ 𐔌  *${prefix}snapcod*
⤷ 𐔌  *${prefix}fakeiphonechat*
⤷ 𐔌  *${prefix}iqc*
⤷ 𐔌  *${prefix}faketweet*
⤷ 𐔌  *${prefix}editimg*
⤷ 𐔌  *${prefix}editimg2*
⤷ 𐔌  *${prefix}toghibli*
⤷ 𐔌  *${prefix}hitamkan*
⤷ 𐔌  *${prefix}bravegreen*
⤷ 𐔌  *${prefix}jadibayi*
⤷ 𐔌  *${prefix}toblack*
⤷ 𐔌  *${prefix}carbon*
⤷ 𐔌  *${prefix}carbonify*
⤷ 𐔌  *${prefix}fakecall*
⤷ 𐔌  *${prefix}fakefb*
⤷ 𐔌  *${prefix}fakestory*
⤷ 𐔌  *${prefix}ustadz*
⤷ 𐔌  *${prefix}ytcomment*
⤷ 𐔌  *${prefix}bagen*
⤷ 𐔌  *${prefix}balogo*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑰𝒔𝒍𝒂𝒎𝒊𝒄 𝑴𝒆𝒏𝒖  〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}kisahnabi*
⤷ 𐔌  *${prefix}asmaulhusna*
⤷ 𐔌  *${prefix}listsurah*
⤷ 𐔌  *${prefix}listsurat*
⤷ 𐔌  *${prefix}sholat*
⤷ 𐔌  *${prefix}jadwalsholat*
⤷ 𐔌  *${prefix}quranaudio*
⤷ 𐔌  *${prefix}alquranaudio*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝐼𝑛𝑡𝑒𝑟𝑛𝑒𝑡 𝑀𝑒𝑛𝑢 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}alquran <114> <1>*
⤷ 𐔌  *${prefix}animeinfo*
⤷ 𐔌  *${prefix}bingimg*
⤷ 𐔌  *${prefix}chargenshin*
⤷ 𐔌  *${prefix}charainfo*
⤷ 𐔌  *${prefix}cloneweb*
⤷ 𐔌  *${prefix}cuaca*
⤷ 𐔌  *${prefix}weather*
⤷ 𐔌  *${prefix}dongeng*
⤷ 𐔌  *${prefix}githubstalk*
⤷ 𐔌  *${prefix}happymod*
⤷ 𐔌  *${prefix}harilibur*
⤷ 𐔌  *${prefix}heroml*
⤷ 𐔌  *${prefix}igstalk*
⤷ 𐔌  *${prefix}youtubestalk*
⤷ 𐔌  *${prefix}ytstalk*
⤷ 𐔌  *${prefix}robloxstalk*
⤷ 𐔌  *${prefix}jadwalsholat*
⤷ 𐔌  *${prefix}kuncigitar*
⤷ 𐔌  *${prefix}news*
⤷ 𐔌  *${prefix}pixabay*
⤷ 𐔌  *${prefix}stalkgenshin*
⤷ 𐔌  *${prefix}stalkml*
⤷ 𐔌  *${prefix}tiktokstalk*
⤷ 𐔌  *${prefix}tiktokstalk*
⤷ 𐔌  *${prefix}ttstalk*
⤷ 𐔌  *${prefix}uhd*
⤷ 𐔌  *${prefix}urutannonton*
⤷ 𐔌  *${prefix}urutannontonanime*
⤷ 𐔌  *${prefix}wattpad*
⤷ 𐔌  *${prefix}wikimedia*
⤷ 𐔌  *${prefix}wikipedia*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝐸𝑑𝑖𝑡𝑜𝑟 𝑃ℎ𝑜𝑡𝑜 𝑀𝑒𝑛𝑢 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}polaroid*
⤷ 𐔌  *${prefix}tompls*
⤷ 𐔌  *${prefix}waifu2x*
⤷ 𐔌  *${prefix}toanime*
⤷ 𐔌  *${prefix}tocomic*
⤷ 𐔌  *${prefix}hdvideo*
⤷ 𐔌  *${prefix}telanjangin*
⤷ 𐔌  *${prefix}toanime*
⤷ 𐔌  *${prefix}tocomic*
⤷ 𐔌  *${prefix}tocyberpunk*
⤷ 𐔌  *${prefix}todisney*
⤷ 𐔌  *${prefix}tomanga*
⤷ 𐔌  *${prefix}toreal*
⤷ 𐔌  *${prefix}tosketch*
⤷ 𐔌  *${prefix}jadizombie*
⤷ 𐔌  *${prefix}tozombie*
⤷ 𐔌  *${prefix}upscale*
⤷ 𐔌  *${prefix}glitchtext*
⤷ 𐔌  *${prefix}writetext*
⤷ 𐔌  *${prefix}advancedglow*
⤷ 𐔌  *${prefix}typographytext*
⤷ 𐔌  *${prefix}pixelglitch*
⤷ 𐔌  *${prefix}neonglitch*
⤷ 𐔌  *${prefix}flagtext*
⤷ 𐔌  *${prefix}flag3dtext*
⤷ 𐔌  *${prefix}deletingtext*
⤷ 𐔌  *${prefix}blackpinkstyle*
⤷ 𐔌  *${prefix}glowingtext*
⤷ 𐔌  *${prefix}underwatertext*
⤷ 𐔌  *${prefix}logomaker*
⤷ 𐔌  *${prefix}cartoonstyle*
⤷ 𐔌  *${prefix}papercutstyle*
⤷ 𐔌  *${prefix}watercolortext*
⤷ 𐔌  *${prefix}effectclouds*
⤷ 𐔌  *${prefix}blackpinklogo*
⤷ 𐔌  *${prefix}gradienttext*
⤷ 𐔌  *${prefix}summerbeach*
⤷ 𐔌  *${prefix}luxurygold*
⤷ 𐔌  *${prefix}multicoloredneon*
⤷ 𐔌  *${prefix}sandsummer*
⤷ 𐔌  *${prefix}galaxywallpaper*
⤷ 𐔌  *${prefix}1917style*
⤷ 𐔌  *${prefix}makingneon*
⤷ 𐔌  *${prefix}royaltext*
⤷ 𐔌  *${prefix}freecreate*
⤷ 𐔌  *${prefix}galaxystyle*
⤷ 𐔌  *${prefix}lighteffects*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑨𝒓𝒕𝒊𝒇𝒊𝒄𝒂𝒍 𝑰𝒏𝒕𝒆𝒍𝒊𝒈𝒆𝒏𝒕 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}ai*
⤷ 𐔌  *${prefix}tosunset*
⤷ 𐔌  *${prefix}tobirthdayboy*
⤷ 𐔌  *${prefix}tochilfree*
⤷ 𐔌  *${prefix}toclimber*
⤷ 𐔌  *${prefix}toyoungboss*
⤷ 𐔌  *${prefix}gebyai*
⤷ 𐔌  *${prefix}gradient*
⤷ 𐔌  *${prefix}editimg*
⤷ 𐔌  *${prefix}editimg2*
⤷ 𐔌  *${prefix}smithai*
⤷ 𐔌  *${prefix}nowartimg*
⤷ 𐔌  *${prefix}nowchat*
⤷ 𐔌  *${prefix}gpt*
⤷ 𐔌  *${prefix}gpt3*
⤷ 𐔌  *${prefix}muslimai*
⤷ 𐔌  *${prefix}metaai*
⤷ 𐔌  *${prefix}toprompt*
⤷ 𐔌  *${prefix}gpt4o*
⤷ 𐔌  *${prefix}gpt5nano*
⤷ 𐔌  *${prefix}gemini*
⤷ 𐔌  *${prefix}deepseek*
⤷ 𐔌  *${prefix}claude*
⤷ 𐔌  *${prefix}grok*
⤷ 𐔌  *${prefix}metaai*
⤷ 𐔌  *${prefix}qwen*
⤷ 𐔌  *${prefix}gpt-5*
⤷ 𐔌  *${prefix}copilot-think*
⤷ 𐔌  *${prefix}copilot*
⤷ 𐔌  *${prefix}sora2*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑷𝒂𝒏𝒆𝒍 𝑷𝒕𝒆𝒓𝒐𝒅𝒂𝒄𝒕𝒚𝒍 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}proses*
⤷ 𐔌  *${prefix}done*
⤷ 𐔌  *${prefix}setdone*
⤷ 𐔌  *${prefix}setproses*
⤷ 𐔌  *${prefix}list*
⤷ 𐔌  *${prefix}store*
⤷ 𐔌  *${prefix}addlist*
⤷ 𐔌  *${prefix}updatelist*
⤷ 𐔌  *${prefix}dellist*
⤷ 𐔌  *${prefix}pushcontact*
⤷ 𐔌  *${prefix}jpmslide*
⤷ 𐔌  *${prefix}jpmbutton*
⤷ 𐔌  *${prefix}jpm*
⤷ 𐔌  *${prefix}pay*
⤷ 𐔌  *${prefix}payment*
⤷ 𐔌  *${prefix}1gb*
⤷ 𐔌  *${prefix}pay*
⤷ 𐔌  *${prefix}payment*
⤷ 𐔌  *${prefix}1gb*
⤷ 𐔌  *${prefix}addseller*
⤷ 𐔌  *${prefix}delseller*
⤷ 𐔌  *${prefix}listseller*
⤷ 𐔌  *${prefix}1gb*
⤷ 𐔌  *${prefix}2gb*
⤷ 𐔌  *${prefix}3gb*
⤷ 𐔌  *${prefix}4gb*
⤷ 𐔌  *${prefix}5gb*
⤷ 𐔌  *${prefix}6gb*
⤷ 𐔌  *${prefix}7gb*
⤷ 𐔌  *${prefix}8gb*
⤷ 𐔌  *${prefix}9gb*
⤷ 𐔌  *${prefix}10gb*
⤷ 𐔌  *${prefix}unli*
⤷ 𐔌  *${prefix}addusr*
⤷ 𐔌  *${prefix}addusradmin*
⤷ 𐔌  *${prefix}listusr*
⤷ 𐔌  *${prefix}listsrv*
⤷ 𐔌  *${prefix}addsrv*
⤷ 𐔌  *${prefix}delsrv*
⤷ 𐔌  *${prefix}deluser*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑷𝒂𝒏𝒆𝒍 𝑷𝒕𝒆𝒓𝒐𝒅𝒂𝒄𝒕𝒚𝒍 𝑽𝟐 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}pay*
⤷ 𐔌  *${prefix}payment*
⤷ 𐔌  *${prefix}1gbv2*
⤷ 𐔌  *${prefix}addsellerv2*
⤷ 𐔌  *${prefix}delsellerv2*
⤷ 𐔌  *${prefix}listsellerv2*
⤷ 𐔌  *${prefix}1gbv2*
⤷ 𐔌  *${prefix}2gbv2*
⤷ 𐔌  *${prefix}3gbv2*
⤷ 𐔌  *${prefix}4gbv2*
⤷ 𐔌  *${prefix}5gbv2*
⤷ 𐔌  *${prefix}6gbv2*
⤷ 𐔌  *${prefix}7gbv2*
⤷ 𐔌  *${prefix}8gbv2*
⤷ 𐔌  *${prefix}9gbv2*
⤷ 𐔌  *${prefix}10gbv2*
⤷ 𐔌  *${prefix}unliv2*
⤷ 𐔌  *${prefix}addusrv2*
⤷ 𐔌  *${prefix}addusradminv2*
⤷ 𐔌  *${prefix}listusrv2*
⤷ 𐔌  *${prefix}listsrv2*
⤷ 𐔌  *${prefix}addsrv2*
⤷ 𐔌  *${prefix}delsrv2*
⤷ 𐔌  *${prefix}deluserv2*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑮𝒓𝒐𝒖𝒑 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}addsesi*
⤷ 𐔌  *${prefix}setslot*
⤷ 𐔌  *${prefix}donepay*
⤷ 𐔌  *${prefix}unpaid*
⤷ 𐔌  *${prefix}uncancel*
⤷ 𐔌  *${prefix}listsesi*
⤷ 𐔌  *${prefix}viewsesi*
⤷ 𐔌  *${prefix}hapussesi*
⤷ 𐔌  *${prefix}mulaiabsen*
⤷ 𐔌  *${prefix}autoai*
⤷ 𐔌  *${prefix}hidetag*
⤷ 𐔌  *${prefix}kick*
⤷ 𐔌  *${prefix}afk*
⤷ 𐔌  *${prefix}tagall*
⤷ 𐔌  *${prefix}delete*
⤷ 𐔌  *${prefix}upswgc*
⤷ 𐔌  *${prefix}del*
⤷ 𐔌  *${prefix}totag*
⤷ 𐔌  *${prefix}listonline*
⤷ 𐔌  *${prefix}group*
⤷ 𐔌  *${prefix}editinfo*
⤷ 𐔌  *${prefix}linkgc*
⤷ 𐔌  *${prefix}adminstats*
⤷ 𐔌  *${prefix}kontribusiadmin*
⤷ 𐔌  *${prefix}statadmin*
⤷ 𐔌  *${prefix}cekid*
⤷ 𐔌  *${prefix}idgc*
⤷ 𐔌  *${prefix}gcl*
⤷ 𐔌  *${prefix}votekick*
⤷ 𐔌  *${prefix}grouptime*
⤷ 𐔌  *${prefix}gctime*
⤷ 𐔌  *${prefix}jadiadmin*
⤷ 𐔌  *${prefix}unadmin*
⤷ 𐔌  *${prefix}totalpesan*
⤷ 𐔌  *${prefix}totalchat*
⤷ 𐔌  *${prefix}promote*
⤷ 𐔌  *${prefix}demote*
⤷ 𐔌  *${prefix}setnamegc*
⤷ 𐔌  *${prefix}antilinkgc*
⤷ 𐔌  *${prefix}tagadmin*
⤷ 𐔌  *${prefix}setppgc*
⤷ 𐔌  *${prefix}sider*
⤷ 𐔌  *${prefix}autodl*
⤷ 𐔌  *${prefix}antilinkgc*
⤷ 𐔌  *${prefix}antilinkgroup*
⤷ 𐔌  *${prefix}antilinkytvid*
⤷ 𐔌  *${prefix}antilinkyoutubevideo*
⤷ 𐔌  *${prefix}antilinkyoutubevid*
⤷ 𐔌  *${prefix}antilinkytch*
⤷ 𐔌  *${prefix}antilinkig*
⤷ 𐔌  *${prefix}antilinkinsta*
⤷ 𐔌  *${prefix}antilinkinstagram*
⤷ 𐔌  *${prefix}antilinkfb*
⤷ 𐔌  *${prefix}antilinkfacebook*
⤷ 𐔌  *${prefix}antilinktg*
⤷ 𐔌  *${prefix}antilinktelegram*
⤷ 𐔌  *${prefix}antilinktt*
⤷ 𐔌  *${prefix}antilinktiktok*
⤷ 𐔌  *${prefix}antilinktwt*
⤷ 𐔌  *${prefix}antilinktwitter*
⤷ 𐔌  *${prefix}antilinktwit*
⤷ 𐔌  *${prefix}antilinkall*
⤷ 𐔌  *${prefix}antitoxic*
⤷ 𐔌  *${prefix}antibadword*
⤷ 𐔌  *${prefix}antiwame*
⤷ 𐔌  *${prefix}antipromo*
⤷ 𐔌  *${prefix}antipromosi*
⤷ 𐔌  *${prefix}delppgc*
⤷ 𐔌  *${prefix}setnamegc*
⤷ 𐔌  *${prefix}getinfogc*
⤷ 𐔌  *${prefix}antitoxic*
⤷ 𐔌  *${prefix}antiaudio*
⤷ 𐔌  *${prefix}antisticker*
⤷ 𐔌  *${prefix}antiimage*
⤷ 𐔌  *${prefix}antivideo*
⤷ 𐔌  *${prefix}rvo*
⤷ 𐔌  *${prefix}readviewonce*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑹𝑷𝑮 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}joinrpg*
⤷ 𐔌  *${prefix}exitrpg*
⤷ 𐔌  *${prefix}myguild*
⤷ 𐔌  *${prefix}guildinfo*
⤷ 𐔌  *${prefix}delguild*
⤷ 𐔌  *${prefix}joinguild*
⤷ 𐔌  *${prefix}open*
⤷ 𐔌  *${prefix}opencreate*
⤷ 𐔌  *${prefix}createguild*
⤷ 𐔌  *${prefix}listguild*
⤷ 𐔌  *${prefix}lamarkerja*
⤷ 𐔌  *${prefix}kerja*
⤷ 𐔌  *${prefix}bankcek*
⤷ 𐔌  *${prefix}maling*
⤷ 𐔌  *${prefix}saham*
⤷ 𐔌  *${prefix}saham-buy*
⤷ 𐔌  *${prefix}saham-sell*
⤷ 𐔌  *${prefix}saham-history*
⤷ 𐔌  *${prefix}mysaham*
⤷ 𐔌  *${prefix}mycoin*
⤷ 𐔌  *${prefix}mycrypto*
⤷ 𐔌  *${prefix}lockbank*
⤷ 𐔌  *${prefix}hackbank*
⤷ 𐔌  *${prefix}banknabung*
⤷ 𐔌  *${prefix}banktarik*
⤷ 𐔌  *${prefix}berkebon*
⤷ 𐔌  *${prefix}crafting*
⤷ 𐔌  *${prefix}bet*
⤷ 𐔌  *${prefix}bonus*
⤷ 𐔌  *${prefix}buah*
⤷ 𐔌  *${prefix}nebang*
⤷ 𐔌  *${prefix}bekerja*
⤷ 𐔌  *${prefix}bansos*
⤷ 𐔌  *${prefix}taxy*
⤷ 𐔌  *${prefix}mulung*
⤷ 𐔌  *${prefix}berburu*
⤷ 𐔌  *${prefix}polisi*
⤷ 𐔌  *${prefix}duel*
⤷ 𐔌  *${prefix}mypets*
⤷ 𐔌  *${prefix}ctiket*
⤷ 𐔌  *${prefix}tukartiket*
⤷ 𐔌  *${prefix}job*
⤷ 𐔌  *${prefix}jobkerja*
⤷ 𐔌  *${prefix}demo*
⤷ 𐔌  *${prefix}demonblood*
⤷ 𐔌  *${prefix}equip*
⤷ 𐔌  *${prefix}gunakan*
⤷ 𐔌  *${prefix}newdungeon*
⤷ 𐔌  *${prefix}magicrank*
⤷ 𐔌  *${prefix}demonslayer*
⤷ 𐔌  *${prefix}santet*
⤷ 𐔌  *${prefix}bangun*
⤷ 𐔌  *${prefix}kerajaan*
⤷ 𐔌  *${prefix}qurbanmenu*
⤷ 𐔌  *${prefix}sertifikatqurban*
⤷ 𐔌  *${prefix}hitungiduladha*
⤷ 𐔌  *${prefix}klaimharian*
⤷ 𐔌  *${prefix}bantuwarga*
⤷ 𐔌  *${prefix}berbagiqurban*
⤷ 𐔌  *${prefix}tugasqurban*
⤷ 𐔌  *${prefix}ceritaqurban*
⤷ 𐔌  *${prefix}lbqurban*
⤷ 𐔌  *${prefix}klaimhadiah*
⤷ 𐔌  *${prefix}reminderqurban*
⤷ 𐔌  *${prefix}genshinimpact*
⤷ 𐔌  *${prefix}hashirakill*
⤷ 𐔌  *${prefix}korpskill*
⤷ 𐔌  *${prefix}hunt*
⤷ 𐔌  *${prefix}hunter*
⤷ 𐔌  *${prefix}gank*
⤷ 𐔌  *${prefix}gankcreate*
⤷ 𐔌  *${prefix}gankrename*
⤷ 𐔌  *${prefix}gankrank*
⤷ 𐔌  *${prefix}gankdelete*
⤷ 𐔌  *${prefix}tawuran*
⤷ 𐔌  *${prefix}dokter*
⤷ 𐔌  *${prefix}berdagang*
⤷ 𐔌  *${prefix}nambang*
⤷ 𐔌  *${prefix}menambang*
⤷ 𐔌  *${prefix}weapon*
⤷ 𐔌  *${prefix}weapons*
⤷ 𐔌  *${prefix}warnet*
⤷ 𐔌  *${prefix}warteg*
⤷ 𐔌  *${prefix}pesanan*
⤷ 𐔌  *${prefix}tutup*
⤷ 𐔌  *${prefix}repair*
⤷ 𐔌  *${prefix}karung*
⤷ 𐔌  *${prefix}sampah*
⤷ 𐔌  *${prefix}createakunyt*
⤷ 𐔌  *${prefix}buatakunyt*
⤷ 𐔌  *${prefix}ytlive*
⤷ 𐔌  *${prefix}youtubelive*
⤷ 𐔌  *${prefix}akunyt*
⤷ 𐔌  *${prefix}akunyoutube*
⤷ 𐔌  *${prefix}rampok*
⤷ 𐔌  *${prefix}saham*
⤷ 𐔌  *${prefix}mysaham*
⤷ 𐔌  *${prefix}mycrypto*
⤷ 𐔌  *${prefix}mycoin*
⤷ 𐔌  *${prefix}rampok*
⤷ 𐔌  *${prefix}bunuh*
⤷ 𐔌  *${prefix}collect*
⤷ 𐔌  *${prefix}mancing*
⤷ 𐔌  *${prefix}pepair*
⤷ 𐔌  *${prefix}feed*
⤷ 𐔌  *${prefix}fight*
⤷ 𐔌  *${prefix}rescue*
⤷ 𐔌  *${prefix}mining*
⤷ 𐔌  *${prefix}gajian*
⤷ 𐔌  *${prefix}upgrade*
⤷ 𐔌  *${prefix}transfer*
⤷ 𐔌  *${prefix}shop*
⤷ 𐔌  *${prefix}shopfish*
⤷ 𐔌  *${prefix}shophewan*
⤷ 𐔌  *${prefix}cipok*
⤷ 𐔌  *${prefix}perangsarung*
⤷ 𐔌  *${prefix}akunxp*
⤷ 𐔌  *${prefix}pemburu*
⤷ 𐔌  *${prefix}kapal*
⤷ 𐔌  *${prefix}giveaway*
⤷ 𐔌  *${prefix}explore*
⤷ 𐔌  *${prefix}guildquest*
⤷ 𐔌  *${prefix}berlayar*
⤷ 𐔌  *${prefix}pilihskill*
⤷ 𐔌  *${prefix}selectskill*
⤷ 𐔌  *${prefix}resetskill*
⤷ 𐔌  *${prefix}harian*
⤷ 𐔌  *${prefix}claim*
⤷ 𐔌  *${prefix}daily*
⤷ 𐔌  *${prefix}detektif*
⤷ 𐔌  *${prefix}selidiki*
⤷ 𐔌  *${prefix}spynamemissions*
⤷ 𐔌  *${prefix}listmisi*
⤷ 𐔌  *${prefix}namamisi*
⤷ 𐔌  *${prefix}mysteryshop*
⤷ 𐔌  *${prefix}monster*
⤷ 𐔌  *${prefix}attack*
⤷ 𐔌  *${prefix}ngaji*
⤷ 𐔌  *${prefix}cekngaji*
⤷ 𐔌  *${prefix}post*
⤷ 𐔌  *${prefix}akunig*
⤷ 𐔌  *${prefix}igpost*
⤷ 𐔌  *${prefix}createig*
⤷ 𐔌  *${prefix}postinstagram*
⤷ 𐔌  *${prefix}posting*
⤷ 𐔌  *${prefix}spyprofile*
⤷ 𐔌  *${prefix}spyprofil*
⤷ 𐔌  *${prefix}spypenyusupanmarkas*
⤷ 𐔌  *${prefix}spyperetasandata*
⤷ 𐔌  *${prefix}spypenyadapanpercakapan*
⤷ 𐔌  *${prefix}spymisipenyamaran*
⤷ 𐔌  *${prefix}spysabotasetarget*
⤷ 𐔌  *${prefix}spypembebasansandera*
⤷ 𐔌  *${prefix}spypenyusupankeamanantinggi*
⤷ 𐔌  *${prefix}spyekstraksivip*
⤷ 𐔌  *${prefix}spypembunuhanrahasia*
⤷ 𐔌  *${prefix}spyinfiltrasibunkermusuh*
⤷ 𐔌  *${prefix}spyoperasifinal*
⤷ 𐔌  *${prefix}transfer*
⤷ 𐔌  *${prefix}training*
⤷ 𐔌  *${prefix}createttt*
⤷ 𐔌  *${prefix}uploadtt*
⤷ 𐔌  *${prefix}uptt*
⤷ 𐔌  *${prefix}akuntiktok*
⤷ 𐔌  *${prefix}work*
⤷ 𐔌  *${prefix}ngepet*
⤷ 𐔌  *${prefix}cook*
⤷ 𐔌  *${prefix}masak*
⤷ 𐔌  *${prefix}memasak*
⤷ 𐔌  *${prefix}eat*
⤷ 𐔌  *${prefix}makan*
⤷ 𐔌  *${prefix}heal*
⤷ 𐔌  *${prefix}shop*
⤷ 𐔌  *${prefix}selectskill*
⤷ 𐔌  *${prefix}sampah*
⤷ 𐔌  *${prefix}roket*
⤷ 𐔌  *${prefix}oject*
⤷ 𐔌  *${prefix}nguli*
⤷ 𐔌  *${prefix}pasar*
⤷ 𐔌  *${prefix}rob*
⤷ 𐔌  *${prefix}referal*
⤷ 𐔌  *${prefix}cipok*
⤷ 𐔌  *${prefix}berkelana*
⤷ 𐔌  *${prefix}petshop*
⤷ 𐔌  *${prefix}misi*
⤷ 𐔌  *${prefix}mision*
⤷ 𐔌  *${prefix}gojek*
⤷ 𐔌  *${prefix}jelajah*
⤷ 𐔌  *${prefix}menjelajah*
⤷ 𐔌  *${prefix}kapal*
⤷ 𐔌  *${prefix}berlayar*
⤷ 𐔌  *${prefix}kolam*
⤷ 𐔌  *${prefix}koboy*
⤷ 𐔌  *${prefix}leaderboard*
⤷ 𐔌  *${prefix}istart*
⤷ 𐔌  *${prefix}iprofile*
⤷ 𐔌  *${prefix}scavenge*
⤷ 𐔌  *${prefix}hunt*
⤷ 𐔌  *${prefix}eat*
⤷ 𐔌  *${prefix}drink*
⤷ 𐔌  *${prefix}craft*
⤷ 𐔌  *${prefix}build*
⤷ 𐔌  *${prefix}rest*
⤷ 𐔌  *${prefix}camp*
⤷ 𐔌  *${prefix}explore*
⤷ 𐔌  *${prefix}fish*
⤷ 𐔌  *${prefix}cook*
⤷ 𐔌  *${prefix}tool*
⤷ 𐔌  *${prefix}weapon*
⤷ 𐔌  *${prefix}upgrade*
⤷ 𐔌  *${prefix}storage*
⤷ 𐔌  *${prefix}map*
⤷ 𐔌  *${prefix}event*
⤷ 𐔌  *${prefix}storm*
⤷ 𐔌  *${prefix}trade*
⤷ 𐔌  *${prefix}market*
⤷ 𐔌  *${prefix}raid*
⤷ 𐔌  *${prefix}safezone*
⤷ 𐔌  *${prefix}leaderboard*
⤷ 𐔌  *${prefix}resetisland*
⤷ 𐔌  *${prefix}mulaimasak*
⤷ 𐔌  *${prefix}cookprofile*
⤷ 𐔌  *${prefix}cookparty*
⤷ 𐔌  *${prefix}cookinvite*
⤷ 𐔌  *${prefix}cookjoin*
⤷ 𐔌  *${prefix}cookleave*
⤷ 𐔌  *${prefix}cookready*
⤷ 𐔌  *${prefix}cookrole*
⤷ 𐔌  *${prefix}cookrecipe*
⤷ 𐔌  *${prefix}cooking*
⤷ 𐔌  *${prefix}cookstep*
⤷ 𐔌  *${prefix}cookhelp*
⤷ 𐔌  *${prefix}cookfix*
⤷ 𐔌  *${prefix}cookserve*
⤷ 𐔌  *${prefix}cookscore*
⤷ 𐔌  *${prefix}cookbattle*
⤷ 𐔌  *${prefix}cookrank*
⤷ 𐔌  *${prefix}cookshop*
⤷ 𐔌  *${prefix}cookupgrade*
⤷ 𐔌  *${prefix}cookevent*
⤷ 𐔌  *${prefix}cookreset*
⤷ 𐔌  *${prefix}cookstart*
⤷ 𐔌  *${prefix}cook*
⤷ 𐔌  *${prefix}cookinv*
⤷ 𐔌  *${prefix}cookbuyer*
⤷ 𐔌  *${prefix}cooksell*
⤷ 𐔌  *${prefix}cookupgrade*
⤷ 𐔌  *${prefix}cookevent*
⤷ 𐔌  *${prefix}cookrank*
⤷ 𐔌  *${prefix}cookreset*
⤷ 𐔌  *${prefix}cookkitchen*
⤷ 𐔌  *${prefix}cookupgrade*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑮𝒆𝒏𝒔𝒉𝒊𝒏 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}build_gi*
⤷ 𐔌  *${prefix}gens-wildlife*
⤷ 𐔌  *${prefix}gens-weapons*
⤷ 𐔌  *${prefix}gens-voiceovers*
⤷ 𐔌  *${prefix}gens-viewpoint*
⤷ 𐔌  *${prefix}gens-talents*
⤷ 𐔌  *${prefix}gens-potion*
⤷ 𐔌  *${prefix}gens-outfit*
⤷ 𐔌  *${prefix}gens-nation*
⤷ 𐔌  *${prefix}gens-namacard*
⤷ 𐔌  *${prefix}gens-materials*
⤷ 𐔌  *${prefix}gens-food*
⤷ 𐔌  *${prefix}gens-enemy*
⤷ 𐔌  *${prefix}gens-emoji*
⤷ 𐔌  *${prefix}gens-domain*
⤷ 𐔌  *${prefix}gens-craft*
⤷ 𐔌  *${prefix}gens-constellation*
⤷ 𐔌  *${prefix}gens-artifact*
⤷ 𐔌  *${prefix}gens-area*
⤷ 𐔌  *${prefix}gens-animals*
⤷ 𐔌  *${prefix}gens-advrank*
⤷ 𐔌  *${prefix}gens-achievement*
⤷ 𐔌  *${prefix}gens-characters*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑸𝒖𝒐𝒕𝒆𝒔 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}quotes-anime*
⤷ 𐔌  *${prefix}quotes-bacot*
⤷ 𐔌  *${prefix}quotes-bijak*
⤷ 𐔌  *${prefix}quotes-bucin*
⤷ 𐔌  *${prefix}quotes-galau*
⤷ 𐔌  *${prefix}quotes-gombal*
⤷ 𐔌  *${prefix}quotes-hacker*
⤷ 𐔌  *${prefix}quotes-islam*
⤷ 𐔌  *${prefix}quotes-motivasi*
⤷ 𐔌  *${prefix}quotes-senja*
⤷ 𐔌  *${prefix}pantun*
⤷ 𐔌  *${prefix}miq*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑮𝒂𝒎𝒆 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}suit*
⤷ 𐔌  *${prefix}suitpvp*
⤷ 𐔌  *${prefix}delsuit*
⤷ 𐔌  *${prefix}deletesuit*
⤷ 𐔌  *${prefix}ttc*
⤷ 𐔌  *${prefix}tictactoe*
⤷ 𐔌  *${prefix}delttc*
⤷ 𐔌  *${prefix}delttt*
⤷ 𐔌  *${prefix}tebakbom*
⤷ 𐔌  *${prefix}petakbom*
⤷ 𐔌  *${prefix}deltebakbom*
⤷ 𐔌  *${prefix}delpetakbom*
⤷ 𐔌  *${prefix}math*
⤷ 𐔌  *${prefix}mathgame*
⤷ 𐔌  *${prefix}ww*
⤷ 𐔌  *${prefix}wwpc*
⤷ 𐔌  *${prefix}werewolf*
⤷ 𐔌  *${prefix}spy*
⤷ 𐔌  *${prefix}war*
⤷ 𐔌  *${prefix}attack*
⤷ 𐔌  *${prefix}ticktactoe*
⤷ 𐔌  *${prefix}tebakgame*
⤷ 𐔌  *${prefix}tebakgambar*
⤷ 𐔌  *${prefix}tebakbendera*
⤷ 𐔌  *${prefix}tebakkata*
⤷ 𐔌  *${prefix}tebaktebakan*
⤷ 𐔌  *${prefix}tebaklirik*
⤷ 𐔌  *${prefix}tebakkimia*
⤷ 𐔌  *${prefix}tebaksiapa*
⤷ 𐔌  *${prefix}tebakkalimat*
⤷ 𐔌  *${prefix}tebakaplikasi*
⤷ 𐔌  *${prefix}tebaklogo*
⤷ 𐔌  *${prefix}tebakhewan*
⤷ 𐔌  *${prefix}tebakjkt48*
⤷ 𐔌  *${prefix}tebakkabupaten*
⤷ 𐔌  *${prefix}tebakff*
⤷ 𐔌  *${prefix}tebakhero*
⤷ 𐔌  *${prefix}tebakgame*
⤷ 𐔌  *${prefix}lengkapikalimat*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑺𝒆𝒂𝒓𝒄𝒉 𝑴𝒆𝒏𝒖  〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}scsearch*
⤷ 𐔌  *${prefix}gsmarena*
⤷ 𐔌  *${prefix}lyrics*
⤷ 𐔌  *${prefix}lirik*
⤷ 𐔌  *${prefix}pin*
⤷ 𐔌  *${prefix}pinterest*
⤷ 𐔌  *${prefix}pinvideo*
⤷ 𐔌  *${prefix}yts*
⤷ 𐔌  *${prefix}youtubesearch*
⤷ 𐔌  *${prefix}applesearch*
⤷ 𐔌  *${prefix}applemusicsearch*
⤷ 𐔌  *${prefix}apmsearch*
⤷ 𐔌  *${prefix}dysearch*
⤷ 𐔌  *${prefix}douyinsearch*
⤷ 𐔌  *${prefix}npm*
⤷ 𐔌  *${prefix}npmjs*
⤷ 𐔌  *${prefix}wallpaper*
⤷ 𐔌  *${prefix}ringtone*
⤷ 𐔌  *${prefix}style*
⤷ 𐔌  *${prefix}bingimg*
⤷ 𐔌  *${prefix}gimage*
⤷ 𐔌  *${prefix}google*
⤷ 𐔌  *${prefix}weather*
⤷ 𐔌  *${prefix}cuaca*
⤷ 𐔌  *${prefix}animeinfo*
⤷ 𐔌  *${prefix}infoanime*
⤷ 𐔌  *${prefix}anime*
⤷ 𐔌  *${prefix}nimeinfo*
⤷ 𐔌  *${prefix}tiktoksearch*
⤷ 𐔌  *${prefix}tiktoks*
⤷ 𐔌  *${prefix}ttsearch*
⤷ 𐔌  *${prefix}nimeinfo*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑫𝒐𝒘𝒏𝒍𝒐𝒂𝒅𝒆𝒓 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}aio*
⤷ 𐔌  *${prefix}douyin*
⤷ 𐔌  *${prefix}bstation*
⤷ 𐔌  *${prefix}gofile*
⤷ 𐔌  *${prefix}snackvideo*
⤷ 𐔌  *${prefix}krakendl*
⤷ 𐔌  *${prefix}krakendownload*
⤷ 𐔌  *${prefix}pixeldrain*
⤷ 𐔌  *${prefix}applemusic*
⤷ 𐔌  *${prefix}apmdl*
⤷ 𐔌  *${prefix}gdrive*
⤷ 𐔌  *${prefix}terabox*
⤷ 𐔌  *${prefix}rednote*
⤷ 𐔌  *${prefix}mega*
⤷ 𐔌  *${prefix}megadl*
⤷ 𐔌  *${prefix}xhs*
⤷ 𐔌  *${prefix}xhsdl*
⤷ 𐔌  *${prefix}xiaohongshu*
⤷ 𐔌  *${prefix}cloud*
⤷ 𐔌  *${prefix}soundcloud*
⤷ 𐔌  *${prefix}qobuz*
⤷ 𐔌  *${prefix}getmodsapk*
⤷ 𐔌  *${prefix}threads*
⤷ 𐔌  *${prefix}reddit*
⤷ 𐔌  *${prefix}twitter*
⤷ 𐔌  *${prefix}instagram*
⤷ 𐔌  *${prefix}igdl*
⤷ 𐔌  *${prefix}facebook*
⤷ 𐔌  *${prefix}fbdl*
⤷ 𐔌  *${prefix}tiktok*
⤷ 𐔌  *${prefix}tiktokaudio*
⤷ 𐔌  *${prefix}ttdl*
⤷ 𐔌  *${prefix}tthd*
⤷ 𐔌  *${prefix}ttaudio*
⤷ 𐔌  *${prefix}youtubedl*
⤷ 𐔌  *${prefix}ytplay*
⤷ 𐔌  *${prefix}ytmp3*
⤷ 𐔌  *${prefix}ytmp4*
⤷ 𐔌  *${prefix}ytdoc*
⤷ 𐔌  *${prefix}mediafire*
⤷ 𐔌  *${prefix}videy*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑴𝒆𝒏𝒖 𝑵𝒔𝒇𝒘 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}hentai*
⤷ 𐔌  *${prefix}listbkp*
⤷ 𐔌  *${prefix}gifhentai*
⤷ 𐔌  *${prefix}gifblowjob*
⤷ 𐔌  *${prefix}hentaivid*
⤷ 𐔌  *${prefix}hneko*
⤷ 𐔌  *${prefix}nwaifu*
⤷ 𐔌  *${prefix}animespank*
⤷ 𐔌  *${prefix}trap*
⤷ 𐔌  *${prefix}gasm*
⤷ 𐔌  *${prefix}ahegao*
⤷ 𐔌  *${prefix}ass*
⤷ 𐔌  *${prefix}bdsm*
⤷ 𐔌  *${prefix}blowjob*
⤷ 𐔌  *${prefix}cuckold*
⤷ 𐔌  *${prefix}cum*
⤷ 𐔌  *${prefix}milf*
⤷ 𐔌  *${prefix}eba*
⤷ 𐔌  *${prefix}ero*
⤷ 𐔌  *${prefix}femdom*
⤷ 𐔌  *${prefix}foot*
⤷ 𐔌  *${prefix}gangbang*
⤷ 𐔌  *${prefix}glasses*
⤷ 𐔌  *${prefix}jahy*
⤷ 𐔌  *${prefix}masturbation*
⤷ 𐔌  *${prefix}mangasearch*
⤷ 𐔌  *${prefix}neko-hentai*
⤷ 𐔌  *${prefix}neko-hentai2*
⤷ 𐔌  *${prefix}nsfwloli*
⤷ 𐔌  *${prefix}orgy*
⤷ 𐔌  *${prefix}panties*
⤷ 𐔌  *${prefix}pussy*
⤷ 𐔌  *${prefix}tentacles*
⤷ 𐔌  *${prefix}thighs*
⤷ 𐔌  *${prefix}yuri*
⤷ 𐔌  *${prefix}zettai*
⤷ 𐔌  *${prefix}xnxxsearch*
⤷ 𐔌  *${prefix}xnxxdl*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑭𝒖𝒏 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}couplepp*
⤷ 𐔌  *${prefix}ppcouple*
⤷ 𐔌  *${prefix}define*
⤷ 𐔌  *${prefix}truth*
⤷ 𐔌  *${prefix}dare*
⤷ 𐔌  *${prefix}jodoh*
⤷ 𐔌  *${prefix}jodohku*
⤷ 𐔌  *${prefix}couple*
⤷ 𐔌  *${prefix}pick*
⤷ 𐔌  *${prefix}quotes*
⤷ 𐔌  *${prefix}can*
⤷ 𐔌  *${prefix}is*
⤷ 𐔌  *${prefix}when*
⤷ 𐔌  *${prefix}what*
⤷ 𐔌  *${prefix}where*
⤷ 𐔌  *${prefix}jadian*
⤷ 𐔌  *${prefix}tembak*
⤷ 𐔌  *${prefix}putus*
⤷ 𐔌  *${prefix}terima*
⤷ 𐔌  *${prefix}tolak*
⤷ 𐔌  *${prefix}moveon*
⤷ 𐔌  *${prefix}where*
⤷ 𐔌  *${prefix}how*
⤷ 𐔌  *${prefix}rate*
⤷ 𐔌  *${prefix}stupidcheck*
⤷ 𐔌  *${prefix}uncleancheck*
⤷ 𐔌  *${prefix}hotcheck*
⤷ 𐔌  *${prefix}smartcheck*
⤷ 𐔌  *${prefix}greatcheck*
⤷ 𐔌  *${prefix}evilcheck*
⤷ 𐔌  *${prefix}dogcheck*
⤷ 𐔌  *${prefix}coolcheck*
⤷ 𐔌  *${prefix}waifucheck*
⤷ 𐔌  *${prefix}checkme*
⤷ 𐔌  *${prefix}cekganteng*
⤷ 𐔌  *${prefix}cekcantik*
⤷ 𐔌  *${prefix}awesomecheck*
⤷ 𐔌  *${prefix}greatcheck*
⤷ 𐔌  *${prefix}gaycheck*
⤷ 𐔌  *${prefix}cutecheck*
⤷ 𐔌  *${prefix}lesbicheck*
⤷ 𐔌  *${prefix}lesbiancheck*
⤷ 𐔌  *${prefix}hornycheck*
⤷ 𐔌  *${prefix}prettycheck*
⤷ 𐔌  *${prefix}lovelycheck*
⤷ 𐔌  *${prefix}uglycheck*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑴𝒆𝒏𝒖 𝑷𝒓𝒊𝒎𝒃𝒐𝒏 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}artimimpi*
⤷ 𐔌  *${prefix}artinama*
⤷ 𐔌  *${prefix}ramalanjodoh*
⤷ 𐔌  *${prefix}ramalanjodohbali*
⤷ 𐔌  *${prefix}suamiistri*
⤷ 𐔌  *${prefix}ramalancinta*
⤷ 𐔌  *${prefix}cocoknama*
⤷ 𐔌  *${prefix}pasangan*
⤷ 𐔌  *${prefix}jadiannikah*
⤷ 𐔌  *${prefix}sifatusaha*
⤷ 𐔌  *${prefix}rezeki*
⤷ 𐔌  *${prefix}pekerjaan*
⤷ 𐔌  *${prefix}nasib*
⤷ 𐔌  *${prefix}penyakit*
⤷ 𐔌  *${prefix}tarot*
⤷ 𐔌  *${prefix}fengshui*
⤷ 𐔌  *${prefix}haribaik*
⤷ 𐔌  *${prefix}harisangar*
⤷ 𐔌  *${prefix}harisial*
⤷ 𐔌  *${prefix}nagahari*
⤷ 𐔌  *${prefix}arahrezeki*
⤷ 𐔌  *${prefix}peruntungan*
⤷ 𐔌  *${prefix}weton*
⤷ 𐔌  *${prefix}karakter*
⤷ 𐔌  *${prefix}keberuntungan*
⤷ 𐔌  *${prefix}memancing*
⤷ 𐔌  *${prefix}masasubur*
⤷ 𐔌  *${prefix}zodiak*
⤷ 𐔌  *${prefix}shio*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑴𝒆𝒏𝒖 𝑺𝒕𝒊𝒄𝒌𝒆𝒓 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}brat*
⤷ 𐔌  *${prefix}bratvideo*
⤷ 𐔌  *${prefix}bratvid*
⤷ 𐔌  *${prefix}sticker*
⤷ 𐔌  *${prefix}stickerwm*
⤷ 𐔌  *${prefix}s*
⤷ 𐔌  *${prefix}swm*
⤷ 𐔌  *${prefix}smeme*
⤷ 𐔌  *${prefix}qc*
⤷ 𐔌  *${prefix}anticolong*
⤷ 𐔌  *${prefix}telesticker*
⤷ 𐔌  *${prefix}telestic*
⤷ 𐔌  *${prefix}stickertele*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑻𝒐𝒐𝒍𝒔 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}tourl*
⤷ 𐔌  *${prefix}shorturl*
⤷ 𐔌  *${prefix}ssweb*
⤷ 𐔌  *${prefix}vcard*
⤷ 𐔌  *${prefix}react*
⤷ 𐔌  *${prefix}kalender*
⤷ 𐔌  *${prefix}clock*
⤷ 𐔌  *${prefix}readmore*
⤷ 𐔌  *${prefix}spoiler*
⤷ 𐔌  *${prefix}hidetext*
⤷ 𐔌  *${prefix}selengkapnya*
⤷ 𐔌  *${prefix}decrypt*
⤷ 𐔌  *${prefix}getprofile*
⤷ 𐔌  *${prefix}toesm*
⤷ 𐔌  *${prefix}tocjs*
⤷ 𐔌  *${prefix}vocalremove*
⤷ 𐔌  *${prefix}removevocal*
⤷ 𐔌  *${prefix}remvocal*
⤷ 𐔌  *${prefix}vocalrem*
⤷ 𐔌  *${prefix}whatmusic*
⤷ 𐔌  *${prefix}ip*
⤷ 𐔌  *${prefix}ipwho*
⤷ 𐔌  *${prefix}cekkartu*
⤷ 𐔌  *${prefix}whatanime*
⤷ 𐔌  *${prefix}getbio*
⤷ 𐔌  *${prefix}qr*
⤷ 𐔌  *${prefix}cekqr*
⤷ 𐔌  *${prefix}toqr*
⤷ 𐔌  *${prefix}enc*
⤷ 𐔌  *${prefix}encrypt*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑴𝒆𝒏𝒖 𝑪𝒐𝒏𝒗𝒆𝒕𝒆𝒓 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}nulis*
⤷ 𐔌  *${prefix}nuliskiri*
⤷ 𐔌  *${prefix}nuliskanan*
⤷ 𐔌  *${prefix}foliokiri*
⤷ 𐔌  *${prefix}foliokanan*
⤷ 𐔌  *${prefix}toqr*
⤷ 𐔌  *${prefix}hd*
⤷ 𐔌  *${prefix}hdimage*
⤷ 𐔌  *${prefix}remini*
⤷ 𐔌  *${prefix}readmore*
⤷ 𐔌  *${prefix}hitamkan*
⤷ 𐔌  *${prefix}toblack*
⤷ 𐔌  *${prefix}topdf*
⤷ 𐔌  *${prefix}toimg*
⤷ 𐔌  *${prefix}toimage*
⤷ 𐔌  *${prefix}bravegreen*
⤷ 𐔌  *${prefix}toptv*
⤷ 𐔌  *${prefix}tovn*
⤷ 𐔌  *${prefix}tomp3*
⤷ 𐔌  *${prefix}toaudio*
⤷ 𐔌  *${prefix}tomp4*
⤷ 𐔌  *${prefix}tovideo*
⤷ 𐔌  *${prefix}tovid*
⤷ 𐔌  *${prefix}jadibayi*
⤷ 𐔌  *${prefix}toghibli*
╰━━━━━━ 𑁍 ━━━━━━╯͙
`}



global.listrpg = (prefix, hias, hituet) => {
return`━━━〔 𝑹𝑷𝑮 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}joinrpg*
⤷ 𐔌  *${prefix}exitrpg*
⤷ 𐔌  *${prefix}myguild*
⤷ 𐔌  *${prefix}guildinfo*
⤷ 𐔌  *${prefix}delguild*
⤷ 𐔌  *${prefix}joinguild*
⤷ 𐔌  *${prefix}open*
⤷ 𐔌  *${prefix}opencreate*
⤷ 𐔌  *${prefix}createguild*
⤷ 𐔌  *${prefix}listguild*
⤷ 𐔌  *${prefix}lamarkerja*
⤷ 𐔌  *${prefix}kerja*
⤷ 𐔌  *${prefix}bankcek*
⤷ 𐔌  *${prefix}maling*
⤷ 𐔌  *${prefix}saham*
⤷ 𐔌  *${prefix}saham-buy*
⤷ 𐔌  *${prefix}saham-sell*
⤷ 𐔌  *${prefix}saham-history*
⤷ 𐔌  *${prefix}mysaham*
⤷ 𐔌  *${prefix}mycoin*
⤷ 𐔌  *${prefix}mycrypto*
⤷ 𐔌  *${prefix}lockbank*
⤷ 𐔌  *${prefix}hackbank*
⤷ 𐔌  *${prefix}banknabung*
⤷ 𐔌  *${prefix}banktarik*
⤷ 𐔌  *${prefix}berkebon*
⤷ 𐔌  *${prefix}crafting*
⤷ 𐔌  *${prefix}bet*
⤷ 𐔌  *${prefix}bonus*
⤷ 𐔌  *${prefix}buah*
⤷ 𐔌  *${prefix}nebang*
⤷ 𐔌  *${prefix}bekerja*
⤷ 𐔌  *${prefix}bansos*
⤷ 𐔌  *${prefix}taxy*
⤷ 𐔌  *${prefix}mulung*
⤷ 𐔌  *${prefix}berburu*
⤷ 𐔌  *${prefix}polisi*
⤷ 𐔌  *${prefix}duel*
⤷ 𐔌  *${prefix}mypets*
⤷ 𐔌  *${prefix}ctiket*
⤷ 𐔌  *${prefix}tukartiket*
⤷ 𐔌  *${prefix}job*
⤷ 𐔌  *${prefix}jobkerja*
⤷ 𐔌  *${prefix}demo*
⤷ 𐔌  *${prefix}demonblood*
⤷ 𐔌  *${prefix}equip*
⤷ 𐔌  *${prefix}gunakan*
⤷ 𐔌  *${prefix}newdungeon*
⤷ 𐔌  *${prefix}magicrank*
⤷ 𐔌  *${prefix}demonslayer*
⤷ 𐔌  *${prefix}santet*
⤷ 𐔌  *${prefix}bangun*
⤷ 𐔌  *${prefix}kerajaan*
⤷ 𐔌  *${prefix}qurbanmenu*
⤷ 𐔌  *${prefix}sertifikatqurban*
⤷ 𐔌  *${prefix}hitungiduladha*
⤷ 𐔌  *${prefix}klaimharian*
⤷ 𐔌  *${prefix}bantuwarga*
⤷ 𐔌  *${prefix}berbagiqurban*
⤷ 𐔌  *${prefix}tugasqurban*
⤷ 𐔌  *${prefix}ceritaqurban*
⤷ 𐔌  *${prefix}lbqurban*
⤷ 𐔌  *${prefix}klaimhadiah*
⤷ 𐔌  *${prefix}reminderqurban*
⤷ 𐔌  *${prefix}genshinimpact*
⤷ 𐔌  *${prefix}hashirakill*
⤷ 𐔌  *${prefix}korpskill*
⤷ 𐔌  *${prefix}hunt*
⤷ 𐔌  *${prefix}hunter*
⤷ 𐔌  *${prefix}gank*
⤷ 𐔌  *${prefix}gankcreate*
⤷ 𐔌  *${prefix}gankrename*
⤷ 𐔌  *${prefix}gankrank*
⤷ 𐔌  *${prefix}gankdelete*
⤷ 𐔌  *${prefix}tawuran*
⤷ 𐔌  *${prefix}dokter*
⤷ 𐔌  *${prefix}berdagang*
⤷ 𐔌  *${prefix}nambang*
⤷ 𐔌  *${prefix}menambang*
⤷ 𐔌  *${prefix}weapon*
⤷ 𐔌  *${prefix}weapons*
⤷ 𐔌  *${prefix}warnet*
⤷ 𐔌  *${prefix}warteg*
⤷ 𐔌  *${prefix}pesanan*
⤷ 𐔌  *${prefix}tutup*
⤷ 𐔌  *${prefix}repair*
⤷ 𐔌  *${prefix}karung*
⤷ 𐔌  *${prefix}sampah*
⤷ 𐔌  *${prefix}createakunyt*
⤷ 𐔌  *${prefix}buatakunyt*
⤷ 𐔌  *${prefix}ytlive*
⤷ 𐔌  *${prefix}youtubelive*
⤷ 𐔌  *${prefix}akunyt*
⤷ 𐔌  *${prefix}akunyoutube*
⤷ 𐔌  *${prefix}rampok*
⤷ 𐔌  *${prefix}saham*
⤷ 𐔌  *${prefix}mysaham*
⤷ 𐔌  *${prefix}mycrypto*
⤷ 𐔌  *${prefix}mycoin*
⤷ 𐔌  *${prefix}rampok*
⤷ 𐔌  *${prefix}bunuh*
⤷ 𐔌  *${prefix}collect*
⤷ 𐔌  *${prefix}mancing*
⤷ 𐔌  *${prefix}pepair*
⤷ 𐔌  *${prefix}feed*
⤷ 𐔌  *${prefix}fight*
⤷ 𐔌  *${prefix}rescue*
⤷ 𐔌  *${prefix}mining*
⤷ 𐔌  *${prefix}gajian*
⤷ 𐔌  *${prefix}upgrade*
⤷ 𐔌  *${prefix}transfer*
⤷ 𐔌  *${prefix}shop*
⤷ 𐔌  *${prefix}shopfish*
⤷ 𐔌  *${prefix}shophewan*
⤷ 𐔌  *${prefix}cipok*
⤷ 𐔌  *${prefix}perangsarung*
⤷ 𐔌  *${prefix}akunxp*
⤷ 𐔌  *${prefix}pemburu*
⤷ 𐔌  *${prefix}kapal*
⤷ 𐔌  *${prefix}giveaway*
⤷ 𐔌  *${prefix}explore*
⤷ 𐔌  *${prefix}guildquest*
⤷ 𐔌  *${prefix}berlayar*
⤷ 𐔌  *${prefix}pilihskill*
⤷ 𐔌  *${prefix}selectskill*
⤷ 𐔌  *${prefix}resetskill*
⤷ 𐔌  *${prefix}harian*
⤷ 𐔌  *${prefix}claim*
⤷ 𐔌  *${prefix}daily*
⤷ 𐔌  *${prefix}detektif*
⤷ 𐔌  *${prefix}selidiki*
⤷ 𐔌  *${prefix}spynamemissions*
⤷ 𐔌  *${prefix}listmisi*
⤷ 𐔌  *${prefix}namamisi*
⤷ 𐔌  *${prefix}mysteryshop*
⤷ 𐔌  *${prefix}monster*
⤷ 𐔌  *${prefix}attack*
⤷ 𐔌  *${prefix}ngaji*
⤷ 𐔌  *${prefix}cekngaji*
⤷ 𐔌  *${prefix}post*
⤷ 𐔌  *${prefix}akunig*
⤷ 𐔌  *${prefix}igpost*
⤷ 𐔌  *${prefix}createig*
⤷ 𐔌  *${prefix}postinstagram*
⤷ 𐔌  *${prefix}posting*
⤷ 𐔌  *${prefix}spyprofile*
⤷ 𐔌  *${prefix}spyprofil*
⤷ 𐔌  *${prefix}spypenyusupanmarkas*
⤷ 𐔌  *${prefix}spyperetasandata*
⤷ 𐔌  *${prefix}spypenyadapanpercakapan*
⤷ 𐔌  *${prefix}spymisipenyamaran*
⤷ 𐔌  *${prefix}spysabotasetarget*
⤷ 𐔌  *${prefix}spypembebasansandera*
⤷ 𐔌  *${prefix}spypenyusupankeamanantinggi*
⤷ 𐔌  *${prefix}spyekstraksivip*
⤷ 𐔌  *${prefix}spypembunuhanrahasia*
⤷ 𐔌  *${prefix}spyinfiltrasibunkermusuh*
⤷ 𐔌  *${prefix}spyoperasifinal*
⤷ 𐔌  *${prefix}transfer*
⤷ 𐔌  *${prefix}training*
⤷ 𐔌  *${prefix}createttt*
⤷ 𐔌  *${prefix}uploadtt*
⤷ 𐔌  *${prefix}uptt*
⤷ 𐔌  *${prefix}akuntiktok*
⤷ 𐔌  *${prefix}work*
⤷ 𐔌  *${prefix}ngepet*
⤷ 𐔌  *${prefix}cook*
⤷ 𐔌  *${prefix}masak*
⤷ 𐔌  *${prefix}memasak*
⤷ 𐔌  *${prefix}eat*
⤷ 𐔌  *${prefix}makan*
⤷ 𐔌  *${prefix}heal*
⤷ 𐔌  *${prefix}shop*
⤷ 𐔌  *${prefix}selectskill*
⤷ 𐔌  *${prefix}sampah*
⤷ 𐔌  *${prefix}roket*
⤷ 𐔌  *${prefix}oject*
⤷ 𐔌  *${prefix}nguli*
⤷ 𐔌  *${prefix}pasar*
⤷ 𐔌  *${prefix}rob*
⤷ 𐔌  *${prefix}referal*
⤷ 𐔌  *${prefix}cipok*
⤷ 𐔌  *${prefix}berkelana*
⤷ 𐔌  *${prefix}petshop*
⤷ 𐔌  *${prefix}misi*
⤷ 𐔌  *${prefix}mision*
⤷ 𐔌  *${prefix}gojek*
⤷ 𐔌  *${prefix}jelajah*
⤷ 𐔌  *${prefix}menjelajah*
⤷ 𐔌  *${prefix}kapal*
⤷ 𐔌  *${prefix}berlayar*
⤷ 𐔌  *${prefix}kolam*
⤷ 𐔌  *${prefix}koboy*
⤷ 𐔌  *${prefix}leaderboard*
⤷ 𐔌  *${prefix}istart*
⤷ 𐔌  *${prefix}iprofile*
⤷ 𐔌  *${prefix}scavenge*
⤷ 𐔌  *${prefix}hunt*
⤷ 𐔌  *${prefix}eat*
⤷ 𐔌  *${prefix}drink*
⤷ 𐔌  *${prefix}craft*
⤷ 𐔌  *${prefix}build*
⤷ 𐔌  *${prefix}rest*
⤷ 𐔌  *${prefix}camp*
⤷ 𐔌  *${prefix}explore*
⤷ 𐔌  *${prefix}fish*
⤷ 𐔌  *${prefix}cook*
⤷ 𐔌  *${prefix}tool*
⤷ 𐔌  *${prefix}weapon*
⤷ 𐔌  *${prefix}upgrade*
⤷ 𐔌  *${prefix}storage*
⤷ 𐔌  *${prefix}map*
⤷ 𐔌  *${prefix}event*
⤷ 𐔌  *${prefix}storm*
⤷ 𐔌  *${prefix}trade*
⤷ 𐔌  *${prefix}market*
⤷ 𐔌  *${prefix}raid*
⤷ 𐔌  *${prefix}safezone*
⤷ 𐔌  *${prefix}leaderboard*
⤷ 𐔌  *${prefix}resetisland*
⤷ 𐔌  *${prefix}mulaimasak*
⤷ 𐔌  *${prefix}cookprofile*
⤷ 𐔌  *${prefix}cookparty*
⤷ 𐔌  *${prefix}cookinvite*
⤷ 𐔌  *${prefix}cookjoin*
⤷ 𐔌  *${prefix}cookleave*
⤷ 𐔌  *${prefix}cookready*
⤷ 𐔌  *${prefix}cookrole*
⤷ 𐔌  *${prefix}cookrecipe*
⤷ 𐔌  *${prefix}cooking*
⤷ 𐔌  *${prefix}cookstep*
⤷ 𐔌  *${prefix}cookhelp*
⤷ 𐔌  *${prefix}cookfix*
⤷ 𐔌  *${prefix}cookserve*
⤷ 𐔌  *${prefix}cookscore*
⤷ 𐔌  *${prefix}cookbattle*
⤷ 𐔌  *${prefix}cookrank*
⤷ 𐔌  *${prefix}cookshop*
⤷ 𐔌  *${prefix}cookupgrade*
⤷ 𐔌  *${prefix}cookevent*
⤷ 𐔌  *${prefix}cookreset*
⤷ 𐔌  *${prefix}cookstart*
⤷ 𐔌  *${prefix}cook*
⤷ 𐔌  *${prefix}cookinv*
⤷ 𐔌  *${prefix}cookbuyer*
⤷ 𐔌  *${prefix}cooksell*
⤷ 𐔌  *${prefix}cookupgrade*
⤷ 𐔌  *${prefix}cookevent*
⤷ 𐔌  *${prefix}cookrank*
⤷ 𐔌  *${prefix}cookreset*
⤷ 𐔌  *${prefix}cookkitchen*
⤷ 𐔌  *${prefix}cookupgrade*
╰━━━━━━ 𑁍 ━━━━━━╯͙
`
}
global.listusr = (prefix, hias, hituet) => {
return`━━━〔 𝑼𝒔𝒆𝒓 𝑴𝒆𝒏𝒖  〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}jadobot*
⤷ 𐔌  *${prefix}stopjadobot*
⤷ 𐔌  *${prefix}listjadibot*
⤷ 𐔌  *${prefix}cupon*
⤷ 𐔌  *${prefix}exp*
⤷ 𐔌  *${prefix}cekexp*
⤷ 𐔌  *${prefix}cooldown*
⤷ 𐔌  *${prefix}cekdarah*
⤷ 𐔌  *${prefix}ping*
⤷ 𐔌  *${prefix}me*
⤷ 𐔌  *${prefix}limit*
⤷ 𐔌  *${prefix}ceklimit*
⤷ 𐔌  *${prefix}buylimit*
⤷ 𐔌  *${prefix}buyglimit*
⤷ 𐔌  *${prefix}cekprem*
⤷ 𐔌  *${prefix}buyglimit*
⤷ 𐔌  *${prefix}mingguan*
⤷ 𐔌  *${prefix}bulanan*
⤷ 𐔌  *${prefix}cekprem*
⤷ 𐔌  *${prefix}daftar*
⤷ 𐔌  *${prefix}register*
⤷ 𐔌  *${prefix}registrasi*
⤷ 𐔌  *${prefix}regmail*
⤷ 𐔌  *${prefix}regismail*
⤷ 𐔌  *${prefix}regmail*
⤷ 𐔌  *${prefix}captcha*
⤷ 𐔌  *${prefix}regkode*
⤷ 𐔌  *${prefix}regcode*
⤷ 𐔌  *${prefix}unreg*
⤷ 𐔌  *${prefix}unregister*
⤷ 𐔌  *${prefix}redeem*
╰━━━━━━ 𑁍 ━━━━━━╯͙`
}
global.toolsm = (prefix, hias, hituet) => {
return`━━━〔 𝑻𝒐𝒐𝒍𝒔 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}tourl*
⤷ 𐔌  *${prefix}shorturl*
⤷ 𐔌  *${prefix}ssweb*
⤷ 𐔌  *${prefix}vcard*
⤷ 𐔌  *${prefix}react*
⤷ 𐔌  *${prefix}kalender*
⤷ 𐔌  *${prefix}clock*
⤷ 𐔌  *${prefix}readmore*
⤷ 𐔌  *${prefix}spoiler*
⤷ 𐔌  *${prefix}hidetext*
⤷ 𐔌  *${prefix}selengkapnya*
⤷ 𐔌  *${prefix}decrypt*
⤷ 𐔌  *${prefix}getprofile*
⤷ 𐔌  *${prefix}toesm*
⤷ 𐔌  *${prefix}tocjs*
⤷ 𐔌  *${prefix}vocalremove*
⤷ 𐔌  *${prefix}removevocal*
⤷ 𐔌  *${prefix}remvocal*
⤷ 𐔌  *${prefix}vocalrem*
⤷ 𐔌  *${prefix}whatmusic*
⤷ 𐔌  *${prefix}ip*
⤷ 𐔌  *${prefix}ipwho*
⤷ 𐔌  *${prefix}cekkartu*
⤷ 𐔌  *${prefix}whatanime*
⤷ 𐔌  *${prefix}getbio*
⤷ 𐔌  *${prefix}qr*
⤷ 𐔌  *${prefix}toqr*
⤷ 𐔌  *${prefix}cekqr*
⤷ 𐔌  *${prefix}enc*
⤷ 𐔌  *${prefix}encrypt*
╰━━━━━━ 𑁍 ━━━━━━╯͙`
}
global.epho = (prefix, hias, hituet) => {
return`━━━〔 𝐸𝑑𝑖𝑡𝑜𝑟 𝑃ℎ𝑜𝑡𝑜 𝑀𝑒𝑛𝑢 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}polaroid*
⤷ 𐔌  *${prefix}tompls*
⤷ 𐔌  *${prefix}waifu2x*
⤷ 𐔌  *${prefix}toanime*
⤷ 𐔌  *${prefix}tocomic*
⤷ 𐔌  *${prefix}hdvideo*
⤷ 𐔌  *${prefix}telanjangin*
⤷ 𐔌  *${prefix}toanime*
⤷ 𐔌  *${prefix}tocomic*
⤷ 𐔌  *${prefix}tocyberpunk*
⤷ 𐔌  *${prefix}todisney*
⤷ 𐔌  *${prefix}tomanga*
⤷ 𐔌  *${prefix}toreal*
⤷ 𐔌  *${prefix}tosketch*
⤷ 𐔌  *${prefix}jadizombie*
⤷ 𐔌  *${prefix}tozombie*
⤷ 𐔌  *${prefix}upscale*
⤷ 𐔌  *${prefix}glitchtext*
⤷ 𐔌  *${prefix}writetext*
⤷ 𐔌  *${prefix}advancedglow*
⤷ 𐔌  *${prefix}typographytext*
⤷ 𐔌  *${prefix}pixelglitch*
⤷ 𐔌  *${prefix}neonglitch*
⤷ 𐔌  *${prefix}flagtext*
⤷ 𐔌  *${prefix}flag3dtext*
⤷ 𐔌  *${prefix}deletingtext*
⤷ 𐔌  *${prefix}blackpinkstyle*
⤷ 𐔌  *${prefix}glowingtext*
⤷ 𐔌  *${prefix}underwatertext*
⤷ 𐔌  *${prefix}logomaker*
⤷ 𐔌  *${prefix}cartoonstyle*
⤷ 𐔌  *${prefix}papercutstyle*
⤷ 𐔌  *${prefix}watercolortext*
⤷ 𐔌  *${prefix}effectclouds*
⤷ 𐔌  *${prefix}blackpinklogo*
⤷ 𐔌  *${prefix}gradienttext*
⤷ 𐔌  *${prefix}summerbeach*
⤷ 𐔌  *${prefix}luxurygold*
⤷ 𐔌  *${prefix}multicoloredneon*
⤷ 𐔌  *${prefix}sandsummer*
⤷ 𐔌  *${prefix}galaxywallpaper*
⤷ 𐔌  *${prefix}1917style*
⤷ 𐔌  *${prefix}makingneon*
⤷ 𐔌  *${prefix}royaltext*
⤷ 𐔌  *${prefix}freecreate*
⤷ 𐔌  *${prefix}galaxystyle*
⤷ 𐔌  *${prefix}lighteffects*
╰━━━━━━ 𑁍 ━━━━━━╯͙`
}
global.lisprimbon = (prefix, hias, hituet) => {
return`━━━〔 𝑴𝒆𝒏𝒖 𝑷𝒓𝒊𝒎𝒃𝒐𝒏 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}artimimpi*
⤷ 𐔌  *${prefix}artinama*
⤷ 𐔌  *${prefix}ramalanjodoh*
⤷ 𐔌  *${prefix}ramalanjodohbali*
⤷ 𐔌  *${prefix}suamiistri*
⤷ 𐔌  *${prefix}ramalancinta*
⤷ 𐔌  *${prefix}cocoknama*
⤷ 𐔌  *${prefix}pasangan*
⤷ 𐔌  *${prefix}jadiannikah*
⤷ 𐔌  *${prefix}sifatusaha*
⤷ 𐔌  *${prefix}rezeki*
⤷ 𐔌  *${prefix}pekerjaan*
⤷ 𐔌  *${prefix}nasib*
⤷ 𐔌  *${prefix}penyakit*
⤷ 𐔌  *${prefix}tarot*
⤷ 𐔌  *${prefix}fengshui*
⤷ 𐔌  *${prefix}haribaik*
⤷ 𐔌  *${prefix}harisangar*
⤷ 𐔌  *${prefix}harisial*
⤷ 𐔌  *${prefix}nagahari*
⤷ 𐔌  *${prefix}arahrezeki*
⤷ 𐔌  *${prefix}peruntungan*
⤷ 𐔌  *${prefix}weton*
⤷ 𐔌  *${prefix}karakter*
⤷ 𐔌  *${prefix}keberuntungan*
⤷ 𐔌  *${prefix}memancing*
⤷ 𐔌  *${prefix}masasubur*
⤷ 𐔌  *${prefix}zodiak*
⤷ 𐔌  *${prefix}shio*
╰━━━━━━ 𑁍 ━━━━━━╯͙`
}

global.nsfwmenu = (prefix, hias, hituet) => {
return`━━━〔 𝑴𝒆𝒏𝒖 𝑵𝒔𝒇𝒘 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}hentai*
⤷ 𐔌  *${prefix}listbkp*
⤷ 𐔌  *${prefix}gifhentai*
⤷ 𐔌  *${prefix}gifblowjob*
⤷ 𐔌  *${prefix}hentaivid*
⤷ 𐔌  *${prefix}hneko*
⤷ 𐔌  *${prefix}nwaifu*
⤷ 𐔌  *${prefix}animespank*
⤷ 𐔌  *${prefix}trap*
⤷ 𐔌  *${prefix}gasm*
⤷ 𐔌  *${prefix}ahegao*
⤷ 𐔌  *${prefix}ass*
⤷ 𐔌  *${prefix}bdsm*
⤷ 𐔌  *${prefix}blowjob*
⤷ 𐔌  *${prefix}cuckold*
⤷ 𐔌  *${prefix}cum*
⤷ 𐔌  *${prefix}milf*
⤷ 𐔌  *${prefix}eba*
⤷ 𐔌  *${prefix}ero*
⤷ 𐔌  *${prefix}femdom*
⤷ 𐔌  *${prefix}foot*
⤷ 𐔌  *${prefix}gangbang*
⤷ 𐔌  *${prefix}glasses*
⤷ 𐔌  *${prefix}jahy*
⤷ 𐔌  *${prefix}masturbation*
⤷ 𐔌  *${prefix}mangasearch*
⤷ 𐔌  *${prefix}neko-hentai*
⤷ 𐔌  *${prefix}neko-hentai2*
⤷ 𐔌  *${prefix}nsfwloli*
⤷ 𐔌  *${prefix}orgy*
⤷ 𐔌  *${prefix}panties*
⤷ 𐔌  *${prefix}pussy*
⤷ 𐔌  *${prefix}tentacles*
⤷ 𐔌  *${prefix}thighs*
⤷ 𐔌  *${prefix}yuri*
⤷ 𐔌  *${prefix}zettai*
⤷ 𐔌  *${prefix}xnxxsearch*
⤷ 𐔌  *${prefix}xnxxdl*
╰━━━━━━ 𑁍 ━━━━━━╯͙
`

}
global.panel = (prefix, hias, hituet) => {
return`
━━━〔 𝑷𝒂𝒏𝒆𝒍 𝑷𝒕𝒆𝒓𝒐𝒅𝒂𝒄𝒕𝒚𝒍 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}proses*
⤷ 𐔌  *${prefix}done*
⤷ 𐔌  *${prefix}setdone*
⤷ 𐔌  *${prefix}setproses*
⤷ 𐔌  *${prefix}list*
⤷ 𐔌  *${prefix}store*
⤷ 𐔌  *${prefix}addlist*
⤷ 𐔌  *${prefix}updatelist*
⤷ 𐔌  *${prefix}dellist*
⤷ 𐔌  *${prefix}pay*
⤷ 𐔌  *${prefix}payment*
⤷ 𐔌  *${prefix}addseller*
⤷ 𐔌  *${prefix}delseller*
⤷ 𐔌  *${prefix}listseller*
⤷ 𐔌  *${prefix}1gb*
⤷ 𐔌  *${prefix}2gb*
⤷ 𐔌  *${prefix}3gb*
⤷ 𐔌  *${prefix}4gb*
⤷ 𐔌  *${prefix}5gb*
⤷ 𐔌  *${prefix}6gb*
⤷ 𐔌  *${prefix}7gb*
⤷ 𐔌  *${prefix}8gb*
⤷ 𐔌  *${prefix}9gb*
⤷ 𐔌  *${prefix}10gb*
⤷ 𐔌  *${prefix}unli*
⤷ 𐔌  *${prefix}addusr*
⤷ 𐔌  *${prefix}addusradmin*
⤷ 𐔌  *${prefix}listusr*
⤷ 𐔌  *${prefix}listsrv*
⤷ 𐔌  *${prefix}addsrv*
⤷ 𐔌  *${prefix}delsrv*
⤷ 𐔌  *${prefix}deluser*
╰━━━━━━ 𑁍 ━━━━━━╯͙`
}

global.panelv2 = (prefix, hias, hituet) => {
return`━━━〔 𝑷𝒂𝒏𝒆𝒍 𝑷𝒕𝒆𝒓𝒐𝒅𝒂𝒄𝒕𝒚𝒍 𝑽𝟐 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}pay*
⤷ 𐔌  *${prefix}payment*
⤷ 𐔌  *${prefix}1gbv2*
⤷ 𐔌  *${prefix}addsellerv2*
⤷ 𐔌  *${prefix}delsellerv2*
⤷ 𐔌  *${prefix}listsellerv2*
⤷ 𐔌  *${prefix}1gbv2*
⤷ 𐔌  *${prefix}2gbv2*
⤷ 𐔌  *${prefix}3gbv2*
⤷ 𐔌  *${prefix}4gbv2*
⤷ 𐔌  *${prefix}5gbv2*
⤷ 𐔌  *${prefix}6gbv2*
⤷ 𐔌  *${prefix}7gbv2*
⤷ 𐔌  *${prefix}8gbv2*
⤷ 𐔌  *${prefix}9gbv2*
⤷ 𐔌  *${prefix}10gbv2*
⤷ 𐔌  *${prefix}unliv2*
⤷ 𐔌  *${prefix}addusrv2*
⤷ 𐔌  *${prefix}addusradminv2*
⤷ 𐔌  *${prefix}listusrv2*
⤷ 𐔌  *${prefix}listsrv2*
⤷ 𐔌  *${prefix}addsrv2*
⤷ 𐔌  *${prefix}delsrv2*
⤷ 𐔌  *${prefix}deluserv2*
╰━━━━━━ 𑁍 ━━━━━━╯͙`
}

global.listown = (prefix, hias, hituet) => {
return`━━━〔 𝑶𝒘𝒏𝒆𝒓 𝑴𝒆𝒏𝒖  〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}self*
⤷ 𐔌  *${prefix}public*
⤷ 𐔌  *${prefix}onlyregis*
⤷ 𐔌  *${prefix}registeronly*
⤷ 𐔌  *${prefix}onlyregister*
⤷ 𐔌  *${prefix}notifregister*
⤷ 𐔌  *${prefix}registernotif*
⤷ 𐔌  *${prefix}notifregis*
⤷ 𐔌  *${prefix}getcase*
⤷ 𐔌  *${prefix}ban*
⤷ 𐔌  *${prefix}unban*
⤷ 𐔌  *${prefix}whitelist*
⤷ 𐔌  *${prefix}unwhitelist*
⤷ 𐔌  *${prefix}blacklist*
⤷ 𐔌  *${prefix}unblacklist*
⤷ 𐔌  *${prefix}delcase*
⤷ 𐔌  *${prefix}listwhitelist*
⤷ 𐔌  *${prefix}cheat*
⤷ 𐔌  *${prefix}cheatall*
⤷ 𐔌  *${prefix}cheatlegendary*
⤷ 𐔌  *${prefix}setppbot*
⤷ 𐔌  *${prefix}setppbotfull*
⤷ 𐔌  *${prefix}setppbotpanjang*
⤷ 𐔌  *${prefix}setbotpp*
⤷ 𐔌  *${prefix}cleartmp*
⤷ 𐔌  *${prefix}deltmp*
⤷ 𐔌  *${prefix}clearcache*
⤷ 𐔌  *${prefix}delcache*
⤷ 𐔌  *${prefix}listblacklist*
⤷ 𐔌  *${prefix}addlimit*
⤷ 𐔌  *${prefix}addsaldo*
⤷ 𐔌  *${prefix}adduang*
⤷ 𐔌  *${prefix}redeemset*
⤷ 𐔌  *${prefix}setredeem*
⤷ 𐔌  *${prefix}delredeem*
⤷ 𐔌  *${prefix}redeemdel*
⤷ 𐔌  *${prefix}delsampah*
⤷ 𐔌  *${prefix}pconly*
⤷ 𐔌  *${prefix}gruponly*
⤷ 𐔌  *${prefix}joinchannel*
⤷ 𐔌  *${prefix}outchannel*
⤷ 𐔌  *${prefix}outgroup*
⤷ 𐔌  *${prefix}joingroup*
⤷ 𐔌  *${prefix}inspect*
⤷ 𐔌  *${prefix}autobio*
⤷ 𐔌  *${prefix}autotype*
⤷ 𐔌  *${prefix}autorecord*
⤷ 𐔌  *${prefix}autorecordtype*
⤷ 𐔌  *${prefix}autorecordtype*
⤷ 𐔌  *${prefix}unavailable*
⤷ 𐔌  *${prefix}autoread*
⤷ 𐔌  *${prefix}shutdown*
⤷ 𐔌  *${prefix}pengingat*
⤷ 𐔌  *${prefix}anticall*
⤷ 𐔌  *${prefix}autoswview*
╰━━━━━━ 𑁍 ━━━━━━╯͙
`
}
global.funmenu = (prefix, hias, hituet) => {
return`━━━〔 𝑭𝒖𝒏 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}couplepp*
⤷ 𐔌  *${prefix}ppcouple*
⤷ 𐔌  *${prefix}define*
⤷ 𐔌  *${prefix}truth*
⤷ 𐔌  *${prefix}dare*
⤷ 𐔌  *${prefix}jodoh*
⤷ 𐔌  *${prefix}jodohku*
⤷ 𐔌  *${prefix}couple*
⤷ 𐔌  *${prefix}pick*
⤷ 𐔌  *${prefix}quotes*
⤷ 𐔌  *${prefix}can*
⤷ 𐔌  *${prefix}is*
⤷ 𐔌  *${prefix}when*
⤷ 𐔌  *${prefix}what*
⤷ 𐔌  *${prefix}jadian*
⤷ 𐔌  *${prefix}tembak*
⤷ 𐔌  *${prefix}putus*
⤷ 𐔌  *${prefix}terima*
⤷ 𐔌  *${prefix}tolak*
⤷ 𐔌  *${prefix}moveon*
⤷ 𐔌  *${prefix}where*
⤷ 𐔌  *${prefix}how*
⤷ 𐔌  *${prefix}rate*
⤷ 𐔌  *${prefix}stupidcheck*
⤷ 𐔌  *${prefix}uncleancheck*
⤷ 𐔌  *${prefix}hotcheck*
⤷ 𐔌  *${prefix}smartcheck*
⤷ 𐔌  *${prefix}greatcheck*
⤷ 𐔌  *${prefix}evilcheck*
⤷ 𐔌  *${prefix}dogcheck*
⤷ 𐔌  *${prefix}coolcheck*
⤷ 𐔌  *${prefix}waifucheck*
⤷ 𐔌  *${prefix}checkme*
⤷ 𐔌  *${prefix}cekganteng*
⤷ 𐔌  *${prefix}cekcantik*
⤷ 𐔌  *${prefix}awesomecheck*
⤷ 𐔌  *${prefix}greatcheck*
⤷ 𐔌  *${prefix}gaycheck*
⤷ 𐔌  *${prefix}cutecheck*
⤷ 𐔌  *${prefix}lesbicheck*
⤷ 𐔌  *${prefix}lesbiancheck*
⤷ 𐔌  *${prefix}hornycheck*
⤷ 𐔌  *${prefix}prettycheck*
⤷ 𐔌  *${prefix}lovelycheck*
⤷ 𐔌  *${prefix}uglycheck*
╰━━━━━━ 𑁍 ━━━━━━╯͙
`
}
global.aimenu = (prefix, hias, hituet) => {
return`━━━〔 𝑨𝒓𝒕𝒊𝒇𝒊𝒄𝒂𝒍 𝑰𝒏𝒕𝒆𝒍𝒊𝒈𝒆𝒏𝒕 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}ai*
⤷ 𐔌  *${prefix}tosunset*
⤷ 𐔌  *${prefix}tobirthdayboy*
⤷ 𐔌  *${prefix}tochilfree*
⤷ 𐔌  *${prefix}toclimber*
⤷ 𐔌  *${prefix}toyoungboss*
⤷ 𐔌  *${prefix}gebyai*
⤷ 𐔌  *${prefix}gradient*
⤷ 𐔌  *${prefix}editimg*
⤷ 𐔌  *${prefix}smithai*
⤷ 𐔌  *${prefix}nowartimg*
⤷ 𐔌  *${prefix}nowchat*
⤷ 𐔌  *${prefix}gpt*
⤷ 𐔌  *${prefix}gpt3*
⤷ 𐔌  *${prefix}muslimai*
⤷ 𐔌  *${prefix}metaai*
⤷ 𐔌  *${prefix}toprompt*
⤷ 𐔌  *${prefix}gpt4o*
⤷ 𐔌  *${prefix}gpt5nano*
⤷ 𐔌  *${prefix}gemini*
⤷ 𐔌  *${prefix}deepseek*
⤷ 𐔌  *${prefix}claude*
⤷ 𐔌  *${prefix}grok*
⤷ 𐔌  *${prefix}metaai*
⤷ 𐔌  *${prefix}gpt-5*
⤷ 𐔌  *${prefix}copilot-think*
⤷ 𐔌  *${prefix}copilot*
⤷ 𐔌  *${prefix}qwen*
⤷ 𐔌  *${prefix}sora2*
╰━━━━━━ 𑁍 ━━━━━━╯͙`
}

global.menuanonym = (prefix, hias, hituet) => {
return`━━━〔 𝑨𝒏𝒐𝒏𝒚𝒎𝒐𝒖𝒔 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}menfes*
⤷ 𐔌  *${prefix}stopmenfess*
⤷ 𐔌  *${prefix}tolakmenfes*
⤷ 𐔌  *${prefix}balasmenfes*
⤷ 𐔌  *${prefix}start*
⤷ 𐔌  *${prefix}mulai*
⤷ 𐔌  *${prefix}anonymouschat*
⤷ 𐔌  *${prefix}sendprofil*
⤷ 𐔌  *${prefix}lanjut*
⤷ 𐔌  *${prefix}neks*
╰━━━━━━ 𑁍 ━━━━━━╯͙
`
}
global.menugenshin = (prefix, hias, hituet) => {
return`━━━〔 𝑮𝒆𝒏𝒔𝒉𝒊𝒏 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}build_gi*
⤷ 𐔌  *${prefix}gens-wildlife*
⤷ 𐔌  *${prefix}gens-weapons*
⤷ 𐔌  *${prefix}gens-voiceovers*
⤷ 𐔌  *${prefix}gens-viewpoint*
⤷ 𐔌  *${prefix}gens-talents*
⤷ 𐔌  *${prefix}gens-potion*
⤷ 𐔌  *${prefix}gens-outfit*
⤷ 𐔌  *${prefix}gens-nation*
⤷ 𐔌  *${prefix}gens-namacard*
⤷ 𐔌  *${prefix}gens-materials*
⤷ 𐔌  *${prefix}gens-food*
⤷ 𐔌  *${prefix}gens-enemy*
⤷ 𐔌  *${prefix}gens-emoji*
⤷ 𐔌  *${prefix}gens-domain*
⤷ 𐔌  *${prefix}gens-craft*
⤷ 𐔌  *${prefix}gens-constellation*
⤷ 𐔌  *${prefix}gens-artifact*
⤷ 𐔌  *${prefix}gens-area*
⤷ 𐔌  *${prefix}gens-animals*
⤷ 𐔌  *${prefix}gens-advrank*
⤷ 𐔌  *${prefix}gens-achievement*
⤷ 𐔌  *${prefix}gens-characters*
╰━━━━━━ 𑁍 ━━━━━━╯͙`
}
global.searchmenu = (prefix, hias, hituet) => {
return`━━━〔 𝑺𝒆𝒂𝒓𝒄𝒉 𝑴𝒆𝒏𝒖  〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}pin*
⤷ 𐔌  *${prefix}scsearch*
⤷ 𐔌  *${prefix}gsmarena*
⤷ 𐔌  *${prefix}lyrics*
⤷ 𐔌  *${prefix}lirik*
⤷ 𐔌  *${prefix}pinterest*
⤷ 𐔌  *${prefix}pinvideo*
⤷ 𐔌  *${prefix}yts*
⤷ 𐔌  *${prefix}youtubesearch*
⤷ 𐔌  *${prefix}applesearch*
⤷ 𐔌  *${prefix}applemusicsearch*
⤷ 𐔌  *${prefix}apmsearch*
⤷ 𐔌  *${prefix}dysearch*
⤷ 𐔌  *${prefix}douyinsearch*
⤷ 𐔌  *${prefix}npm*
⤷ 𐔌  *${prefix}npmjs*
⤷ 𐔌  *${prefix}wallpaper*
⤷ 𐔌  *${prefix}ringtone*
⤷ 𐔌  *${prefix}style*
⤷ 𐔌  *${prefix}bingimg*
⤷ 𐔌  *${prefix}gimage*
⤷ 𐔌  *${prefix}google*
⤷ 𐔌  *${prefix}weather*
⤷ 𐔌  *${prefix}cuaca*
⤷ 𐔌  *${prefix}animeinfo*
⤷ 𐔌  *${prefix}infoanime*
⤷ 𐔌  *${prefix}anime*
⤷ 𐔌  *${prefix}nimeinfo*
⤷ 𐔌  *${prefix}tiktoksearch*
⤷ 𐔌  *${prefix}tiktoks*
⤷ 𐔌  *${prefix}ttsearch*
⤷ 𐔌  *${prefix}nimeinfo*
╰━━━━━━ 𑁍 ━━━━━━╯͙
`
}
global.quotes = (prefix, hias, hituet) => {
return`━━━〔 𝑸𝒖𝒐𝒕𝒆𝒔 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}quotes-anime*
⤷ 𐔌  *${prefix}quotes-bacot*
⤷ 𐔌  *${prefix}quotes-bijak*
⤷ 𐔌  *${prefix}quotes-bucin*
⤷ 𐔌  *${prefix}quotes-galau*
⤷ 𐔌  *${prefix}quotes-gombal*
⤷ 𐔌  *${prefix}quotes-hacker*
⤷ 𐔌  *${prefix}quotes-islam*
⤷ 𐔌  *${prefix}quotes-motivasi*
⤷ 𐔌  *${prefix}quotes-senja*
⤷ 𐔌  *${prefix}pantun*
⤷ 𐔌  *${prefix}miq*
╰━━━━━━ 𑁍 ━━━━━━╯͙͙
`
}
global.bugmenu = (prefix, hias, hituet) => {
return`━━━〔 𝑩𝒖𝒈 𝑫𝒆𝒍𝒂𝒚 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}invis-delay*
⤷ 𐔌  *${prefix}invis-drak*
⤷ 𐔌  *${prefix}invis-bulldozer*
⤷ 𐔌  *${prefix}invis-hard*
╰━━━━━━ 𑁍 ━━━━━━╯͙

━━━〔 𝑩𝒖𝒈 𝑪𝒓𝒂𝒔𝒉 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}crash-invis*
⤷ 𐔌  *${prefix}crash-andro*
⤷ 𐔌  *${prefix}rxma-crasher*
⤷ 𐔌  *${prefix}fatal-notif*
⤷ 𐔌  *${prefix}rxmaXhard*
⤷ 𐔌  *${prefix}hard-crasher*
⤷ 𐔌  *${prefix}dozervip*
⤷ 𐔌  *${prefix}invis-whatsapp*
⤷ 𐔌  *${prefix}forclose-asupan*
⤷ 𐔌  *${prefix}combo-hard*
╰━━━━━━ 𑁍 ━━━━━━╯͙
`
}
global.maker = (prefix, hias, hituet) => {
return`━━━〔 𝑴𝒂𝒌𝒆𝒓 𝑴𝒆𝒏𝒖  〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}snapcode*
⤷ 𐔌  *${prefix}snapcod*
⤷ 𐔌  *${prefix}fakeiphonechat*
⤷ 𐔌  *${prefix}iqc*
⤷ 𐔌  *${prefix}faketweet*
⤷ 𐔌  *${prefix}editimg*
⤷ 𐔌  *${prefix}toghibli*
⤷ 𐔌  *${prefix}hitamkan*
⤷ 𐔌  *${prefix}bravegreen*
⤷ 𐔌  *${prefix}jadibayi*
⤷ 𐔌  *${prefix}toblack*
⤷ 𐔌  *${prefix}carbon*
⤷ 𐔌  *${prefix}carbonify*
⤷ 𐔌  *${prefix}fakecall*
⤷ 𐔌  *${prefix}fakefb*
⤷ 𐔌  *${prefix}fakestory*
⤷ 𐔌  *${prefix}ustadz*
⤷ 𐔌  *${prefix}ytcomment*
⤷ 𐔌  *${prefix}bagen*
⤷ 𐔌  *${prefix}balogo*
╰━━━━━━ 𑁍 ━━━━━━╯͙`
}
global.voice = (prefix, hias, hituet) => {
return`━━━〔 𝑽𝒐𝒊𝒄𝒆 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}kobo*
⤷ 𐔌  *${prefix}tokobo*
⤷ 𐔌  *${prefix}zeta*
⤷ 𐔌  *${prefix}tozeta*
⤷ 𐔌  *${prefix}voicejokowi*
⤷ 𐔌  *${prefix}alya*
⤷ 𐔌  *${prefix}voicejokowi*
⤷ 𐔌  *${prefix}voiceprabowo*
⤷ 𐔌  *${prefix}voicemegawati*
╰━━━━━━ 𑁍 ━━━━━━╯͙`
}
global.berita = (prefix, hias, hituet) => {
return`​━━━〔 𝑩𝒂𝒓𝒊𝒕𝒂 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  ${prefix}kompas
⤷ 𐔌  ${prefix}tribunnews
⤷ 𐔌  ${prefix}liputan6
⤷ 𐔌  ${prefix}sindonews
⤷ 𐔌  ${prefix}cnbc
⤷ 𐔌  ${prefix}cnbcindo
⤷ 𐔌  ${prefix}cnbcindonesia
⤷ 𐔌  ${prefix}merdeka
⤷ 𐔌  ${prefix}beritamerdeka
⤷ 𐔌  ${prefix}antara
⤷ 𐔌  ${prefix}antaranews
⤷ 𐔌  ${prefix}beritaantara
╰━━━━━━ 𑁍 ━━━━━━╯͙`
}
global.groupmenu = (prefix, hias, hituet) => {
return`━━━〔 𝑮𝒓𝒐𝒖𝒑 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}addsesi*
⤷ 𐔌  *${prefix}setslot*
⤷ 𐔌  *${prefix}donepay*
⤷ 𐔌  *${prefix}unpaid*
⤷ 𐔌  *${prefix}uncancel*
⤷ 𐔌  *${prefix}listsesi*
⤷ 𐔌  *${prefix}viewsesi*
⤷ 𐔌  *${prefix}hapussesi*
⤷ 𐔌  *${prefix}mulaiabsen*
⤷ 𐔌  *${prefix}autoai*
⤷ 𐔌  *${prefix}hidetag*
⤷ 𐔌  *${prefix}kick*
⤷ 𐔌  *${prefix}afk*
⤷ 𐔌  *${prefix}tagall*
⤷ 𐔌  *${prefix}delete*
⤷ 𐔌  *${prefix}del*
⤷ 𐔌  *${prefix}totag*
⤷ 𐔌  *${prefix}listonline*
⤷ 𐔌  *${prefix}upswgc*
⤷ 𐔌  *${prefix}group*
⤷ 𐔌  *${prefix}editinfo*
⤷ 𐔌  *${prefix}linkgc*
⤷ 𐔌  *${prefix}promote*
⤷ 𐔌  *${prefix}demote*
⤷ 𐔌  *${prefix}setnamegc*
⤷ 𐔌  *${prefix}tagadmin*
⤷ 𐔌  *${prefix}adminstats*
⤷ 𐔌  *${prefix}kontribusiadmin*
⤷ 𐔌  *${prefix}statadmin*
⤷ 𐔌  *${prefix}cekid*
⤷ 𐔌  *${prefix}idgc*
⤷ 𐔌  *${prefix}gcl*
⤷ 𐔌  *${prefix}votekick*
⤷ 𐔌  *${prefix}grouptime*
⤷ 𐔌  *${prefix}gctime*
⤷ 𐔌  *${prefix}jadiadmin*
⤷ 𐔌  *${prefix}unadmin*
⤷ 𐔌  *${prefix}totalpesan*
⤷ 𐔌  *${prefix}totalchat*
⤷ 𐔌  *${prefix}setppgc*
⤷ 𐔌  *${prefix}sider*
⤷ 𐔌  *${prefix}autodl*
⤷ 𐔌  *${prefix}antilinkgc*
⤷ 𐔌  *${prefix}antilinkgroup*
⤷ 𐔌  *${prefix}antilinkytvid*
⤷ 𐔌  *${prefix}antilinkyoutubevideo*
⤷ 𐔌  *${prefix}antilinkyoutubevid*
⤷ 𐔌  *${prefix}antilinkytch*
⤷ 𐔌  *${prefix}antilinkig*
⤷ 𐔌  *${prefix}'antilinkinsta*
⤷ 𐔌  *${prefix}antilinkinstagram*
⤷ 𐔌  *${prefix}antilinkfb*
⤷ 𐔌  *${prefix}antilinkfacebook*
⤷ 𐔌  *${prefix}antilinktg*
⤷ 𐔌  *${prefix}antilinktelegram*
⤷ 𐔌  *${prefix}antilinktt*
⤷ 𐔌  *${prefix}antilinktiktok*
⤷ 𐔌  *${prefix}antilinktwt*
⤷ 𐔌  *${prefix}antilinktwitter*
⤷ 𐔌  *${prefix}antilinktwit*
⤷ 𐔌  *${prefix}antilinkall*
⤷ 𐔌  *${prefix}antitoxic*
⤷ 𐔌  *${prefix}antibadword*
⤷ 𐔌  *${prefix}antiwame*
⤷ 𐔌  *${prefix}antipromo*
⤷ 𐔌  *${prefix}antipromosi*
⤷ 𐔌  *${prefix}delppgc*
⤷ 𐔌  *${prefix}setnamegc*
⤷ 𐔌  *${prefix}getinfogc*
⤷ 𐔌  *${prefix}antitoxic*
⤷ 𐔌  *${prefix}antiaudio*
⤷ 𐔌  *${prefix}antisticker*
⤷ 𐔌  *${prefix}antiimage*
⤷ 𐔌  *${prefix}antivideo*
⤷ 𐔌  *${prefix}rvo*
⤷ 𐔌  *${prefix}readviewonce*
╰━━━━━━ 𑁍 ━━━━━━╯͙`
}
global.downloadmenu = (prefix, hias, hituet) => {
return`━━━〔 𝑫𝒐𝒘𝒏𝒍𝒐𝒂𝒅𝒆𝒓 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}aio*
⤷ 𐔌  *${prefix}douyin*
⤷ 𐔌  *${prefix}bstation*
⤷ 𐔌  *${prefix}gofile*
⤷ 𐔌  *${prefix}snackvideo*
⤷ 𐔌  *${prefix}krakendl*
⤷ 𐔌  *${prefix}krakendownload*
⤷ 𐔌  *${prefix}pixeldrain*
⤷ 𐔌  *${prefix}applemusic*
⤷ 𐔌  *${prefix}apmdl*
⤷ 𐔌  *${prefix}gdrive*
⤷ 𐔌  *${prefix}terabox*
⤷ 𐔌  *${prefix}rednote*
⤷ 𐔌  *${prefix}mega*
⤷ 𐔌  *${prefix}megadl*
⤷ 𐔌  *${prefix}xhs*
⤷ 𐔌  *${prefix}xhsdl*
⤷ 𐔌  *${prefix}xiaohongshu*
⤷ 𐔌  *${prefix}cloud*
⤷ 𐔌  *${prefix}soundcloud*
⤷ 𐔌  *${prefix}qobuz*
⤷ 𐔌  *${prefix}getmodsapk*
⤷ 𐔌  *${prefix}threads*
⤷ 𐔌  *${prefix}reddit*
⤷ 𐔌  *${prefix}twitter*
⤷ 𐔌  *${prefix}instagram*
⤷ 𐔌  *${prefix}igdl*
⤷ 𐔌  *${prefix}facebook*
⤷ 𐔌  *${prefix}fbdl*
⤷ 𐔌  *${prefix}tiktok*
⤷ 𐔌  *${prefix}tiktokaudio*
⤷ 𐔌  *${prefix}ttdl*
⤷ 𐔌  *${prefix}tthd*
⤷ 𐔌  *${prefix}ttaudio*
⤷ 𐔌  *${prefix}youtubedl*
⤷ 𐔌  *${prefix}ytplay*
⤷ 𐔌  *${prefix}ytmp3*
⤷ 𐔌  *${prefix}ytmp4*
⤷ 𐔌  *${prefix}ytdoc*
⤷ 𐔌  *${prefix}mediafire*
⤷ 𐔌  *${prefix}videy*
╰━━━━━━ 𑁍 ━━━━━━╯͙`
}
global.stickermenu = (prefix, hias, hituet) => {
return`━━━〔 𝑴𝒆𝒏𝒖 𝑺𝒕𝒊𝒄𝒌𝒆𝒓 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}brat*
⤷ 𐔌  *${prefix}bratvideo*
⤷ 𐔌  *${prefix}bratvid*
⤷ 𐔌  *${prefix}sticker*
⤷ 𐔌  *${prefix}stickerwm*
⤷ 𐔌  *${prefix}s*
⤷ 𐔌  *${prefix}swm*
⤷ 𐔌  *${prefix}smeme*
⤷ 𐔌  *${prefix}anticolong*
⤷ 𐔌  *${prefix}telesticker*
⤷ 𐔌  *${prefix}telestic*
⤷ 𐔌  *${prefix}stickertele*
⤷ 𐔌  *${prefix}qc*
⤷ 𐔌  *${prefix}ttp*
╰━━━━━━ 𑁍 ━━━━━━╯͙`
}
global.imageconver = (prefix, hias, hituet) => {
return`━━━〔 𝑴𝒆𝒏𝒖 𝑪𝒐𝒏𝒗𝒆𝒕𝒆𝒓 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}nulis*
⤷ 𐔌  *${prefix}nuliskiri*
⤷ 𐔌  *${prefix}nuliskanan*
⤷ 𐔌  *${prefix}foliokiri*
⤷ 𐔌  *${prefix}foliokanan*
⤷ 𐔌  *${prefix}toqr*
⤷ 𐔌  *${prefix}hd*
⤷ 𐔌  *${prefix}hdimage*
⤷ 𐔌  *${prefix}remini*
⤷ 𐔌  *${prefix}readmore*
⤷ 𐔌  *${prefix}hitamkan*
⤷ 𐔌  *${prefix}toblack*
⤷ 𐔌  *${prefix}toimg*
⤷ 𐔌  *${prefix}toimage*
⤷ 𐔌  *${prefix}bravegreen*
⤷ 𐔌  *${prefix}toptv*
⤷ 𐔌  *${prefix}tovn*
⤷ 𐔌  *${prefix}tomp3*
⤷ 𐔌  *${prefix}toaudio*
⤷ 𐔌  *${prefix}tomp4*
⤷ 𐔌  *${prefix}tovideo*
⤷ 𐔌  *${prefix}tovid*
⤷ 𐔌  *${prefix}jadibayi*
⤷ 𐔌  *${prefix}toghibli*
╰━━━━━━ 𑁍 ━━━━━━╯͙`
}
global.gamemenu = (prefix, hias, hituet) => {
return`━━━〔 𝑮𝒂𝒎𝒆 𝑴𝒆𝒏𝒖 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}suit*
⤷ 𐔌  *${prefix}suitpvp*
⤷ 𐔌  *${prefix}delsuit*
⤷ 𐔌  *${prefix}deletesuit*
⤷ 𐔌  *${prefix}ttc*
⤷ 𐔌  *${prefix}tictactoe*
⤷ 𐔌  *${prefix}delttc*
⤷ 𐔌  *${prefix}delttt*
⤷ 𐔌  *${prefix}tebakbom*
⤷ 𐔌  *${prefix}petakbom*
⤷ 𐔌  *${prefix}deltebakbom*
⤷ 𐔌  *${prefix}delpetakbom*
⤷ 𐔌  *${prefix}math*
⤷ 𐔌  *${prefix}mathgame*
⤷ 𐔌  *${prefix}ww*
⤷ 𐔌  *${prefix}wwpc*
⤷ 𐔌  *${prefix}werewolf*
⤷ 𐔌  *${prefix}spy*
⤷ 𐔌  *${prefix}war*
⤷ 𐔌  *${prefix}attack*
⤷ 𐔌  *${prefix}ticktactoe*
⤷ 𐔌  *${prefix}tebakgame*
⤷ 𐔌  *${prefix}tebakgambar*
⤷ 𐔌  *${prefix}tebakbendera*
⤷ 𐔌  *${prefix}tebakkata*
⤷ 𐔌  *${prefix}tebaktebakan*
⤷ 𐔌  *${prefix}tebaklirik*
⤷ 𐔌  *${prefix}tebakkimia*
⤷ 𐔌  *${prefix}tebaksiapa*
⤷ 𐔌  *${prefix}tebakkalimat*
⤷ 𐔌  *${prefix}tebakaplikasi*
⤷ 𐔌  *${prefix}tebaklogo*
⤷ 𐔌  *${prefix}tebakhewan*
⤷ 𐔌  *${prefix}tebakjkt48*
⤷ 𐔌  *${prefix}tebakkabupaten*
⤷ 𐔌  *${prefix}tebakff*
⤷ 𐔌  *${prefix}tebakhero*
⤷ 𐔌  *${prefix}tebakgame*
⤷ 𐔌  *${prefix}lengkapikalimat*
╰━━━━━━ 𑁍 ━━━━━━╯͙`
}
global.islammenu = (prefix, hias, hituet) => {
return`
━━━〔 𝑰𝒔𝒍𝒂𝒎𝒊𝒄 𝑴𝒆𝒏𝒖  〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}kisahnabi*
⤷ 𐔌  *${prefix}asmaulhusna*
⤷ 𐔌  *${prefix}listsurah*
⤷ 𐔌  *${prefix}listsurat*
⤷ 𐔌  *${prefix}sholat*
⤷ 𐔌  *${prefix}jadwalsholat*
⤷ 𐔌  *${prefix}quranaudio*
⤷ 𐔌  *${prefix}alquranaudio*
╰━━━━━━ 𑁍 ━━━━━━╯͙`
}

global.intermenu = (prefix, hias, hituet) => {
return`━━━〔 𝐼𝑛𝑡𝑒𝑟𝑛𝑒𝑡 𝑀𝑒𝑛𝑢 〕━━━┈ ✿͙
⤷ 𐔌  *${prefix}alquran <114> <1>*
⤷ 𐔌  *${prefix}animeinfo*
⤷ 𐔌  *${prefix}bingimg*
⤷ 𐔌  *${prefix}chargenshin*
⤷ 𐔌  *${prefix}charainfo*
⤷ 𐔌  *${prefix}cloneweb*
⤷ 𐔌  *${prefix}cuaca*
⤷ 𐔌  *${prefix}weather*
⤷ 𐔌  *${prefix}dongeng*
⤷ 𐔌  *${prefix}githubstalk*
⤷ 𐔌  *${prefix}happymod*
⤷ 𐔌  *${prefix}harilibur*
⤷ 𐔌  *${prefix}heroml*
⤷ 𐔌  *${prefix}igstalk*
⤷ 𐔌  *${prefix}youtubestalk*
⤷ 𐔌  *${prefix}ytstalk*
⤷ 𐔌  *${prefix}robloxstalk*
⤷ 𐔌  *${prefix}jadwalsholat*
⤷ 𐔌  *${prefix}kuncigitar*
⤷ 𐔌  *${prefix}news*
⤷ 𐔌  *${prefix}pixabay*
⤷ 𐔌  *${prefix}stalkgenshin*
⤷ 𐔌  *${prefix}stalkml*
⤷ 𐔌  *${prefix}tiktokstalk*
⤷ 𐔌  *${prefix}tiktokstalk*
⤷ 𐔌  *${prefix}ttstalk*
⤷ 𐔌  *${prefix}uhd*
⤷ 𐔌  *${prefix}urutannonton*
⤷ 𐔌  *${prefix}urutannontonanime*
⤷ 𐔌  *${prefix}wattpad*
⤷ 𐔌  *${prefix}wikimedia*
⤷ 𐔌  *${prefix}wikipedia*
╰━━━━━━ 𑁍 ━━━━━━╯͙`
}

let file = require.resolve(__filename)
fs.watchFile(file, () => {
	fs.unwatchFile(file)
	console.log(chalk.redBright(`Update ${__filename}`))
	delete require.cache[file]
	require(file)
})
